# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_4/base_xbar_4.xci
# IP: The module: 'base_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_xbar_4/base_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_4/base_xbar_4.xci
# IP: The module: 'base_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_xbar_4/base_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
