-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    delay_samples : IN STD_LOGIC_VECTOR (31 downto 0);
    feedback_gain : IN STD_LOGIC_VECTOR (31 downto 0);
    wet_mix : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of audio is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "audio_audio,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=0,HLS_SYN_FF=1635,HLS_SYN_LUT=1203,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal out_L : STD_LOGIC_VECTOR (31 downto 0);
    signal out_L_ap_vld : STD_LOGIC;
    signal out_R : STD_LOGIC_VECTOR (31 downto 0);
    signal out_R_ap_vld : STD_LOGIC;
    signal in_L : STD_LOGIC_VECTOR (31 downto 0);
    signal in_R : STD_LOGIC_VECTOR (31 downto 0);
    signal write_index : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal delay_buffer_L_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal delay_buffer_R_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln38_fu_182_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln38_reg_453 : STD_LOGIC_VECTOR (12 downto 0);
    signal wet_mix_read_reg_468 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal in_R_read_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_L_read_reg_478 : STD_LOGIC_VECTOR (31 downto 0);
    signal delayed_L_reg_483 : STD_LOGIC_VECTOR (31 downto 0);
    signal delayed_R_reg_488 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_fu_215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_reg_493 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln64_fu_225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_166_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln64_reg_530 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln64_fu_247_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln64_reg_536 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_158_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln65_reg_541 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln65_fu_251_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln65_reg_547 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_170_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln66_reg_552 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln66_fu_255_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln66_reg_558 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_162_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln67_reg_563 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln67_fu_259_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln67_reg_569 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln64_1_reg_574 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln65_1_reg_579 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln66_1_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln67_1_reg_589 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln41_fu_192_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_fu_210_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln74_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal delay_buffer_L_ce0_local : STD_LOGIC;
    signal delay_buffer_L_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal delay_buffer_L_we0_local : STD_LOGIC;
    signal delay_buffer_R_ce0_local : STD_LOGIC;
    signal delay_buffer_R_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal delay_buffer_R_we0_local : STD_LOGIC;
    signal grp_fu_158_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_162_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_166_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln82_fu_174_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal read_index_fu_186_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln64_fu_263_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal sub_ln65_1_fu_278_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal sub_ln66_fu_293_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal sub_ln67_fu_308_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_fu_323_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln64_1_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln64_2_fu_335_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_352_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln65_2_fu_359_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln65_2_fu_364_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_381_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln66_1_fu_388_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln66_2_fu_393_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln67_1_fu_417_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln67_2_fu_422_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln65_fu_373_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln64_fu_344_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln67_fu_431_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln66_fu_402_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_mul_32ns_32s_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component audio_mul_32s_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component audio_delay_buffer_L_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component audio_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        out_L : IN STD_LOGIC_VECTOR (31 downto 0);
        out_L_ap_vld : IN STD_LOGIC;
        out_R : IN STD_LOGIC_VECTOR (31 downto 0);
        out_R_ap_vld : IN STD_LOGIC;
        in_L : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_R : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    delay_buffer_L_U : component audio_delay_buffer_L_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => delay_buffer_L_address0_local,
        ce0 => delay_buffer_L_ce0_local,
        we0 => delay_buffer_L_we0_local,
        d0 => in_L,
        q0 => delay_buffer_L_q0);

    delay_buffer_R_U : component audio_delay_buffer_L_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => delay_buffer_R_address0_local,
        ce0 => delay_buffer_R_ce0_local,
        we0 => delay_buffer_R_we0_local,
        d0 => in_R,
        q0 => delay_buffer_R_q0);

    control_s_axi_U : component audio_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        out_L => out_L,
        out_L_ap_vld => out_L_ap_vld,
        out_R => out_R,
        out_R_ap_vld => out_R_ap_vld,
        in_L => in_L,
        in_R => in_R,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32ns_32s_64_2_1_U1 : component audio_mul_32ns_32s_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_158_p0,
        din1 => in_L_read_reg_478,
        ce => ap_const_logic_1,
        dout => grp_fu_158_p2);

    mul_32ns_32s_64_2_1_U2 : component audio_mul_32ns_32s_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_162_p0,
        din1 => in_R_read_reg_473,
        ce => ap_const_logic_1,
        dout => grp_fu_162_p2);

    mul_32s_32ns_64_2_1_U3 : component audio_mul_32s_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => delayed_L_reg_483,
        din1 => grp_fu_166_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_166_p2);

    mul_32s_32ns_64_2_1_U4 : component audio_mul_32s_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => delayed_R_reg_488,
        din1 => grp_fu_170_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_170_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                delayed_L_reg_483 <= delay_buffer_L_q0;
                delayed_R_reg_488 <= delay_buffer_R_q0;
                in_L_read_reg_478 <= in_L;
                in_R_read_reg_473 <= in_R;
                sub_ln65_reg_493 <= sub_ln65_fu_215_p2;
                wet_mix_read_reg_468 <= wet_mix;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                mul_ln64_reg_530 <= grp_fu_166_p2;
                mul_ln65_reg_541 <= grp_fu_158_p2;
                mul_ln66_reg_552 <= grp_fu_170_p2;
                mul_ln67_reg_563 <= grp_fu_162_p2;
                trunc_ln64_reg_536 <= trunc_ln64_fu_247_p1;
                trunc_ln65_reg_547 <= trunc_ln65_fu_251_p1;
                trunc_ln66_reg_558 <= trunc_ln66_fu_255_p1;
                trunc_ln67_reg_569 <= trunc_ln67_fu_259_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln38_reg_453 <= trunc_ln38_fu_182_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln64_1_reg_574 <= sub_ln64_fu_263_p2(39 downto 8);
                trunc_ln65_1_reg_579 <= sub_ln65_1_fu_278_p2(39 downto 8);
                trunc_ln66_1_reg_584 <= sub_ln66_fu_293_p2(39 downto 8);
                trunc_ln67_1_reg_589 <= sub_ln67_fu_308_p2(39 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                write_index <= add_ln74_fu_198_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln74_fu_198_p2 <= std_logic_vector(unsigned(write_index) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    delay_buffer_L_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, zext_ln41_fu_192_p1, zext_ln60_fu_210_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_L_address0_local <= zext_ln60_fu_210_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            delay_buffer_L_address0_local <= zext_ln41_fu_192_p1(13 - 1 downto 0);
        else 
            delay_buffer_L_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    delay_buffer_L_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            delay_buffer_L_ce0_local <= ap_const_logic_1;
        else 
            delay_buffer_L_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_L_we0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_L_we0_local <= ap_const_logic_1;
        else 
            delay_buffer_L_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_R_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, zext_ln41_fu_192_p1, zext_ln60_fu_210_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_R_address0_local <= zext_ln60_fu_210_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            delay_buffer_R_address0_local <= zext_ln41_fu_192_p1(13 - 1 downto 0);
        else 
            delay_buffer_R_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    delay_buffer_R_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            delay_buffer_R_ce0_local <= ap_const_logic_1;
        else 
            delay_buffer_R_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_R_we0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_R_we0_local <= ap_const_logic_1;
        else 
            delay_buffer_R_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_158_p0 <= zext_ln65_fu_234_p1(32 - 1 downto 0);
    grp_fu_162_p0 <= zext_ln65_fu_234_p1(32 - 1 downto 0);
    grp_fu_166_p1 <= zext_ln64_fu_225_p1(32 - 1 downto 0);
    grp_fu_170_p1 <= zext_ln64_fu_225_p1(32 - 1 downto 0);
    out_L <= std_logic_vector(unsigned(select_ln65_fu_373_p3) + unsigned(select_ln64_fu_344_p3));

    out_L_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_L_ap_vld <= ap_const_logic_1;
        else 
            out_L_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_R <= std_logic_vector(unsigned(select_ln67_fu_431_p3) + unsigned(select_ln66_fu_402_p3));

    out_R_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_R_ap_vld <= ap_const_logic_1;
        else 
            out_R_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    read_index_fu_186_p2 <= std_logic_vector(unsigned(trunc_ln38_fu_182_p1) - unsigned(trunc_ln82_fu_174_p1));
    select_ln64_fu_344_p3 <= 
        sub_ln64_1_fu_330_p2 when (tmp_fu_323_p3(0) = '1') else 
        trunc_ln64_2_fu_335_p4;
    select_ln65_fu_373_p3 <= 
        sub_ln65_2_fu_359_p2 when (tmp_1_fu_352_p3(0) = '1') else 
        trunc_ln65_2_fu_364_p4;
    select_ln66_fu_402_p3 <= 
        sub_ln66_1_fu_388_p2 when (tmp_2_fu_381_p3(0) = '1') else 
        trunc_ln66_2_fu_393_p4;
    select_ln67_fu_431_p3 <= 
        sub_ln67_1_fu_417_p2 when (tmp_3_fu_410_p3(0) = '1') else 
        trunc_ln67_2_fu_422_p4;
    sub_ln64_1_fu_330_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln64_1_reg_574));
    sub_ln64_fu_263_p2 <= std_logic_vector(unsigned(ap_const_lv40_0) - unsigned(trunc_ln64_reg_536));
    sub_ln65_1_fu_278_p2 <= std_logic_vector(unsigned(ap_const_lv40_0) - unsigned(trunc_ln65_reg_547));
    sub_ln65_2_fu_359_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln65_1_reg_579));
    sub_ln65_fu_215_p2 <= std_logic_vector(unsigned(ap_const_lv32_100) - unsigned(wet_mix));
    sub_ln66_1_fu_388_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln66_1_reg_584));
    sub_ln66_fu_293_p2 <= std_logic_vector(unsigned(ap_const_lv40_0) - unsigned(trunc_ln66_reg_558));
    sub_ln67_1_fu_417_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln67_1_reg_589));
    sub_ln67_fu_308_p2 <= std_logic_vector(unsigned(ap_const_lv40_0) - unsigned(trunc_ln67_reg_569));
    tmp_1_fu_352_p3 <= mul_ln65_reg_541(63 downto 63);
    tmp_2_fu_381_p3 <= mul_ln66_reg_552(63 downto 63);
    tmp_3_fu_410_p3 <= mul_ln67_reg_563(63 downto 63);
    tmp_fu_323_p3 <= mul_ln64_reg_530(63 downto 63);
    trunc_ln38_fu_182_p1 <= write_index(13 - 1 downto 0);
    trunc_ln64_2_fu_335_p4 <= mul_ln64_reg_530(39 downto 8);
    trunc_ln64_fu_247_p1 <= grp_fu_166_p2(40 - 1 downto 0);
    trunc_ln65_2_fu_364_p4 <= mul_ln65_reg_541(39 downto 8);
    trunc_ln65_fu_251_p1 <= grp_fu_158_p2(40 - 1 downto 0);
    trunc_ln66_2_fu_393_p4 <= mul_ln66_reg_552(39 downto 8);
    trunc_ln66_fu_255_p1 <= grp_fu_170_p2(40 - 1 downto 0);
    trunc_ln67_2_fu_422_p4 <= mul_ln67_reg_563(39 downto 8);
    trunc_ln67_fu_259_p1 <= grp_fu_162_p2(40 - 1 downto 0);
    trunc_ln82_fu_174_p1 <= delay_samples(13 - 1 downto 0);
    zext_ln41_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_index_fu_186_p2),64));
    zext_ln60_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln38_reg_453),64));
    zext_ln64_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(wet_mix_read_reg_468),64));
    zext_ln65_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln65_reg_493),64));
end behav;
