// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.923000,HLS_SYN_LAT=11,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=12722,HLS_SYN_LUT=7614,HLS_VERSION=2024_2}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y,
        y_ap_vld,
        x
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] y;
output   y_ap_vld;
input  [31:0] x;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [31:0] p_ZZ3firPiiE9shift_reg_126;
reg   [31:0] p_ZZ3firPiiE9shift_reg_125;
reg   [31:0] p_ZZ3firPiiE9shift_reg_124;
reg   [31:0] p_ZZ3firPiiE9shift_reg_123;
reg   [31:0] p_ZZ3firPiiE9shift_reg_122;
reg   [31:0] p_ZZ3firPiiE9shift_reg_121;
reg   [31:0] p_ZZ3firPiiE9shift_reg_120;
reg   [31:0] p_ZZ3firPiiE9shift_reg_119;
reg   [31:0] p_ZZ3firPiiE9shift_reg_118;
reg   [31:0] p_ZZ3firPiiE9shift_reg_117;
reg   [31:0] p_ZZ3firPiiE9shift_reg_116;
reg   [31:0] p_ZZ3firPiiE9shift_reg_115;
reg   [31:0] p_ZZ3firPiiE9shift_reg_114;
reg   [31:0] p_ZZ3firPiiE9shift_reg_113;
reg   [31:0] p_ZZ3firPiiE9shift_reg_112;
reg   [31:0] p_ZZ3firPiiE9shift_reg_111;
reg   [31:0] p_ZZ3firPiiE9shift_reg_110;
reg   [31:0] p_ZZ3firPiiE9shift_reg_109;
reg   [31:0] p_ZZ3firPiiE9shift_reg_108;
reg   [31:0] p_ZZ3firPiiE9shift_reg_107;
reg   [31:0] p_ZZ3firPiiE9shift_reg_106;
reg   [31:0] p_ZZ3firPiiE9shift_reg_105;
reg   [31:0] p_ZZ3firPiiE9shift_reg_104;
reg   [31:0] p_ZZ3firPiiE9shift_reg_103;
reg   [31:0] p_ZZ3firPiiE9shift_reg_102;
reg   [31:0] p_ZZ3firPiiE9shift_reg_101;
reg   [31:0] p_ZZ3firPiiE9shift_reg_100;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_99;
reg   [31:0] p_ZZ3firPiiE9shift_reg_98;
reg   [31:0] p_ZZ3firPiiE9shift_reg_97;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_96;
reg   [31:0] p_ZZ3firPiiE9shift_reg_95;
reg   [31:0] p_ZZ3firPiiE9shift_reg_94;
reg   [31:0] p_ZZ3firPiiE9shift_reg_93;
reg   [31:0] p_ZZ3firPiiE9shift_reg_92;
reg   [31:0] p_ZZ3firPiiE9shift_reg_91;
reg   [31:0] p_ZZ3firPiiE9shift_reg_90;
reg   [31:0] p_ZZ3firPiiE9shift_reg_89;
reg   [31:0] p_ZZ3firPiiE9shift_reg_88;
reg   [31:0] p_ZZ3firPiiE9shift_reg_87;
reg   [31:0] p_ZZ3firPiiE9shift_reg_86;
reg   [31:0] p_ZZ3firPiiE9shift_reg_85;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_84;
reg   [31:0] p_ZZ3firPiiE9shift_reg_83;
reg   [31:0] p_ZZ3firPiiE9shift_reg_82;
reg   [31:0] p_ZZ3firPiiE9shift_reg_81;
reg   [31:0] p_ZZ3firPiiE9shift_reg_80;
reg   [31:0] p_ZZ3firPiiE9shift_reg_79;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78;
reg   [31:0] p_ZZ3firPiiE9shift_reg_77;
reg   [31:0] p_ZZ3firPiiE9shift_reg_76;
reg   [31:0] p_ZZ3firPiiE9shift_reg_75;
reg   [31:0] p_ZZ3firPiiE9shift_reg_74;
reg   [31:0] p_ZZ3firPiiE9shift_reg_73;
reg   [31:0] p_ZZ3firPiiE9shift_reg_72;
reg   [31:0] p_ZZ3firPiiE9shift_reg_71;
reg   [31:0] p_ZZ3firPiiE9shift_reg_70;
reg   [31:0] p_ZZ3firPiiE9shift_reg_69;
reg   [31:0] p_ZZ3firPiiE9shift_reg_68;
reg   [31:0] p_ZZ3firPiiE9shift_reg_67;
reg   [31:0] p_ZZ3firPiiE9shift_reg_66;
reg   [31:0] p_ZZ3firPiiE9shift_reg_65;
reg   [31:0] p_ZZ3firPiiE9shift_reg_64;
reg   [31:0] p_ZZ3firPiiE9shift_reg_63;
reg   [31:0] p_ZZ3firPiiE9shift_reg_62;
reg   [31:0] p_ZZ3firPiiE9shift_reg_61;
reg   [31:0] p_ZZ3firPiiE9shift_reg_60;
reg   [31:0] p_ZZ3firPiiE9shift_reg_59;
reg   [31:0] p_ZZ3firPiiE9shift_reg_58;
reg   [31:0] p_ZZ3firPiiE9shift_reg_57;
reg   [31:0] p_ZZ3firPiiE9shift_reg_56;
reg   [31:0] p_ZZ3firPiiE9shift_reg_55;
reg   [31:0] p_ZZ3firPiiE9shift_reg_54;
reg   [31:0] p_ZZ3firPiiE9shift_reg_53;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_52;
reg   [31:0] p_ZZ3firPiiE9shift_reg_51;
reg   [31:0] p_ZZ3firPiiE9shift_reg_50;
reg   [31:0] p_ZZ3firPiiE9shift_reg_49;
reg   [31:0] p_ZZ3firPiiE9shift_reg_48;
reg   [31:0] p_ZZ3firPiiE9shift_reg_47;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46;
reg   [31:0] p_ZZ3firPiiE9shift_reg_45;
reg   [31:0] p_ZZ3firPiiE9shift_reg_44;
reg   [31:0] p_ZZ3firPiiE9shift_reg_43;
reg   [31:0] p_ZZ3firPiiE9shift_reg_42;
reg   [31:0] p_ZZ3firPiiE9shift_reg_41;
reg   [31:0] p_ZZ3firPiiE9shift_reg_40;
reg   [31:0] p_ZZ3firPiiE9shift_reg_39;
reg   [31:0] p_ZZ3firPiiE9shift_reg_38;
reg   [31:0] p_ZZ3firPiiE9shift_reg_37;
reg   [31:0] p_ZZ3firPiiE9shift_reg_36;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_35;
reg   [31:0] p_ZZ3firPiiE9shift_reg_34;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_33;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_32;
reg   [31:0] p_ZZ3firPiiE9shift_reg_31;
reg   [31:0] p_ZZ3firPiiE9shift_reg_30;
reg   [31:0] p_ZZ3firPiiE9shift_reg_29;
reg   [31:0] p_ZZ3firPiiE9shift_reg_28;
reg   [31:0] p_ZZ3firPiiE9shift_reg_27;
reg   [31:0] p_ZZ3firPiiE9shift_reg_26;
reg   [31:0] p_ZZ3firPiiE9shift_reg_25;
reg   [31:0] p_ZZ3firPiiE9shift_reg_24;
reg   [31:0] p_ZZ3firPiiE9shift_reg_23;
reg   [31:0] p_ZZ3firPiiE9shift_reg_22;
reg   [31:0] p_ZZ3firPiiE9shift_reg_21;
reg   [31:0] p_ZZ3firPiiE9shift_reg_20;
reg   [31:0] p_ZZ3firPiiE9shift_reg_19;
reg   [31:0] p_ZZ3firPiiE9shift_reg_18;
reg   [31:0] p_ZZ3firPiiE9shift_reg_17;
reg   [31:0] p_ZZ3firPiiE9shift_reg_16;
reg   [31:0] p_ZZ3firPiiE9shift_reg_15;
reg   [31:0] p_ZZ3firPiiE9shift_reg_14;
reg   [31:0] p_ZZ3firPiiE9shift_reg_13;
reg   [31:0] p_ZZ3firPiiE9shift_reg_12;
reg   [31:0] p_ZZ3firPiiE9shift_reg_11;
reg   [31:0] p_ZZ3firPiiE9shift_reg_10;
reg   [31:0] fir_int_int_shift_reg_9;
reg   [31:0] fir_int_int_shift_reg_8;
reg   [31:0] fir_int_int_shift_reg_7;
reg   [31:0] fir_int_int_shift_reg_6;
reg   [31:0] fir_int_int_shift_reg_5;
reg  signed [31:0] fir_int_int_shift_reg_4;
reg   [31:0] fir_int_int_shift_reg_3;
reg   [31:0] fir_int_int_shift_reg_2;
reg   [31:0] fir_int_int_shift_reg_1;
reg   [31:0] fir_int_int_shift_reg;
reg   [31:0] x_read_reg_3160;
wire    ap_block_pp0_stage0_11001;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_97_load_reg_3166;
reg   [31:0] fir_int_int_shift_reg_reg_3177;
reg   [31:0] fir_int_int_shift_reg_reg_3177_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_88_load_reg_3183;
reg   [31:0] p_ZZ3firPiiE9shift_reg_88_load_reg_3183_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_9_reg_3189;
reg   [31:0] fir_int_int_shift_reg_9_reg_3189_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_11_reg_3199;
reg   [31:0] fir_int_int_shift_reg_11_reg_3199_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_12_reg_3205;
reg   [31:0] p_ZZ3firPiiE9shift_reg_79_load_reg_3210;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter2_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter3_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter4_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter5_reg;
reg  signed [31:0] p_ZZ3firPiiE9shift_reg_67_load_reg_3221;
reg   [31:0] p_ZZ3firPiiE9shift_reg_66_load_reg_3226;
reg   [31:0] p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter2_reg;
reg   [31:0] fir_int_int_shift_reg_26_reg_3231;
reg   [31:0] fir_int_int_shift_reg_26_reg_3231_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_26_reg_3231_pp0_iter2_reg;
reg   [31:0] fir_int_int_shift_reg_28_reg_3241;
reg   [31:0] fir_int_int_shift_reg_28_reg_3241_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_50_load_reg_3247;
reg   [31:0] p_ZZ3firPiiE9shift_reg_50_load_reg_3247_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter2_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter3_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter4_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter5_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter6_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter7_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter8_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter2_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter3_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter4_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter5_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter6_reg;
reg   [31:0] fir_int_int_shift_reg_29_reg_3258_pp0_iter7_reg;
reg   [31:0] fir_int_int_shift_reg_33_reg_3264;
reg   [31:0] fir_int_int_shift_reg_33_reg_3264_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_40_load_reg_3270;
reg   [31:0] p_ZZ3firPiiE9shift_reg_37_load_reg_3276;
reg   [31:0] p_ZZ3firPiiE9shift_reg_36_load_reg_3281;
reg   [31:0] fir_int_int_shift_reg_35_reg_3292;
reg   [31:0] fir_int_int_shift_reg_35_reg_3292_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_17_load_reg_3307;
reg   [31:0] fir_int_int_shift_reg_5_load_reg_3312;
reg   [31:0] fir_int_int_shift_reg_5_load_reg_3312_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_3_load_reg_3322;
reg   [31:0] fir_int_int_shift_reg_3_load_reg_3322_pp0_iter1_reg;
reg   [31:0] fir_int_int_shift_reg_2_load_reg_3328;
wire   [31:0] sub_ln44_3_fu_1311_p2;
reg   [31:0] sub_ln44_3_reg_3333;
wire   [31:0] sub_ln44_9_fu_1335_p2;
reg   [31:0] sub_ln44_9_reg_3338;
wire   [31:0] add_ln44_16_fu_1359_p2;
reg   [31:0] add_ln44_16_reg_3343;
reg   [31:0] add_ln44_16_reg_3343_pp0_iter1_reg;
wire  signed [31:0] add_ln44_17_fu_1365_p2;
reg  signed [31:0] add_ln44_17_reg_3349;
wire   [31:0] add_ln44_87_fu_1377_p2;
reg   [31:0] add_ln44_87_reg_3354;
reg   [31:0] add_ln44_87_reg_3354_pp0_iter1_reg;
wire   [31:0] sub_ln44_21_fu_1401_p2;
reg   [31:0] sub_ln44_21_reg_3360;
wire   [31:0] sub_ln44_23_fu_1425_p2;
reg   [31:0] sub_ln44_23_reg_3365;
wire   [31:0] add_ln44_116_fu_1461_p2;
reg   [31:0] add_ln44_116_reg_3370;
wire   [31:0] add_ln44_49_fu_1473_p2;
reg   [31:0] add_ln44_49_reg_3375;
reg   [31:0] add_ln44_49_reg_3375_pp0_iter1_reg;
reg   [31:0] add_ln44_49_reg_3375_pp0_iter2_reg;
reg   [31:0] add_ln44_49_reg_3375_pp0_iter3_reg;
reg   [31:0] add_ln44_49_reg_3375_pp0_iter4_reg;
reg   [31:0] add_ln44_49_reg_3375_pp0_iter5_reg;
wire   [31:0] add_ln44_53_fu_1491_p2;
reg   [31:0] add_ln44_53_reg_3381;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter1_reg;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter2_reg;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter3_reg;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter4_reg;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter5_reg;
reg   [31:0] add_ln44_53_reg_3381_pp0_iter6_reg;
wire   [31:0] add_ln44_55_fu_1497_p2;
reg   [31:0] add_ln44_55_reg_3387;
reg   [31:0] add_ln44_55_reg_3387_pp0_iter1_reg;
reg   [31:0] add_ln44_55_reg_3387_pp0_iter2_reg;
wire   [31:0] add_ln44_56_fu_1503_p2;
reg   [31:0] add_ln44_56_reg_3394;
reg   [31:0] add_ln44_56_reg_3394_pp0_iter1_reg;
reg   [31:0] add_ln44_56_reg_3394_pp0_iter2_reg;
reg   [31:0] add_ln44_56_reg_3394_pp0_iter3_reg;
wire  signed [31:0] add_ln44_59_fu_1509_p2;
reg  signed [31:0] add_ln44_59_reg_3399;
wire   [31:0] add_ln44_63_fu_1515_p2;
reg   [31:0] add_ln44_63_reg_3404;
wire   [31:0] add_ln44_64_fu_1521_p2;
reg   [31:0] add_ln44_64_reg_3409;
wire   [31:0] add_ln44_68_fu_1539_p2;
reg   [31:0] add_ln44_68_reg_3414;
wire  signed [31:0] add_ln44_70_fu_1545_p2;
reg  signed [31:0] add_ln44_70_reg_3419;
wire   [31:0] sub_ln44_33_fu_1569_p2;
reg   [31:0] sub_ln44_33_reg_3424;
reg   [31:0] sub_ln44_33_reg_3424_pp0_iter1_reg;
reg   [31:0] sub_ln44_33_reg_3424_pp0_iter2_reg;
wire   [31:0] sub_ln44_35_fu_1593_p2;
reg   [31:0] sub_ln44_35_reg_3429;
wire   [31:0] sub_ln44_39_fu_1629_p2;
reg   [31:0] sub_ln44_39_reg_3434;
wire   [31:0] sub_ln44_41_fu_1653_p2;
reg   [31:0] sub_ln44_41_reg_3439;
wire   [31:0] sub_ln44_43_fu_1677_p2;
reg   [31:0] sub_ln44_43_reg_3444;
wire   [31:0] sub_ln44_45_fu_1707_p2;
reg   [31:0] sub_ln44_45_reg_3449;
wire   [31:0] add_ln44_6_fu_1725_p2;
reg   [31:0] add_ln44_6_reg_3454;
wire  signed [31:0] add_ln44_7_fu_1731_p2;
reg  signed [31:0] add_ln44_7_reg_3460;
wire   [31:0] add_ln44_127_fu_1743_p2;
reg   [31:0] add_ln44_127_reg_3465;
reg   [31:0] add_ln44_127_reg_3465_pp0_iter1_reg;
wire   [31:0] add_ln44_129_fu_1755_p2;
reg   [31:0] add_ln44_129_reg_3470;
reg   [31:0] add_ln44_129_reg_3470_pp0_iter1_reg;
wire   [31:0] add_ln44_131_fu_1761_p2;
reg   [31:0] add_ln44_131_reg_3475;
wire   [31:0] add_ln44_19_fu_1773_p2;
reg   [31:0] add_ln44_19_reg_3480;
wire   [31:0] add_ln44_26_fu_1785_p2;
reg   [31:0] add_ln44_26_reg_3485;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter1_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter2_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter3_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter4_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter5_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter6_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter7_reg;
reg   [31:0] add_ln44_26_reg_3485_pp0_iter8_reg;
wire   [31:0] add_ln44_39_fu_1791_p2;
reg   [31:0] add_ln44_39_reg_3491;
reg   [31:0] add_ln44_39_reg_3491_pp0_iter1_reg;
wire   [31:0] add_ln44_79_fu_1803_p2;
reg   [31:0] add_ln44_79_reg_3497;
wire   [31:0] sub_ln44_57_fu_1833_p2;
reg   [31:0] sub_ln44_57_reg_3503;
reg   [31:0] sub_ln44_57_reg_3503_pp0_iter1_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_107_load_reg_3508;
reg   [31:0] p_ZZ3firPiiE9shift_reg_101_load_reg_3514;
reg   [31:0] p_ZZ3firPiiE9shift_reg_100_load_reg_3519;
reg   [31:0] p_ZZ3firPiiE9shift_reg_100_load_reg_3519_pp0_iter2_reg;
reg   [31:0] p_ZZ3firPiiE9shift_reg_98_load_reg_3530;
reg   [31:0] p_ZZ3firPiiE9shift_reg_98_load_reg_3530_pp0_iter2_reg;
wire   [31:0] sub_ln44_5_fu_1956_p2;
reg   [31:0] sub_ln44_5_reg_3535;
wire   [31:0] sub_ln44_11_fu_1986_p2;
reg   [31:0] sub_ln44_11_reg_3540;
wire   [31:0] grp_fu_1341_p2;
reg   [31:0] mul_ln44_4_reg_3545;
wire   [31:0] grp_fu_1347_p2;
reg   [31:0] mul_ln44_6_reg_3550;
wire   [31:0] add_ln44_12_fu_2007_p2;
reg   [31:0] add_ln44_12_reg_3555;
reg   [31:0] add_ln44_12_reg_3555_pp0_iter2_reg;
reg   [31:0] add_ln44_12_reg_3555_pp0_iter3_reg;
wire   [31:0] add_ln44_110_fu_2028_p2;
reg   [31:0] add_ln44_110_reg_3560;
wire   [31:0] grp_fu_1443_p2;
reg   [31:0] mul_ln44_19_reg_3565;
reg   [31:0] mul_ln44_19_reg_3565_pp0_iter2_reg;
wire   [31:0] add_ln44_69_fu_2048_p2;
reg   [31:0] add_ln44_69_reg_3570;
reg   [31:0] add_ln44_69_reg_3570_pp0_iter2_reg;
wire   [31:0] add_ln44_75_fu_2062_p2;
reg   [31:0] add_ln44_75_reg_3576;
wire   [31:0] grp_fu_1599_p2;
reg   [31:0] mul_ln44_5_reg_3581;
wire   [31:0] grp_fu_1605_p2;
reg   [31:0] mul_ln44_9_reg_3586;
wire   [31:0] grp_fu_1683_p2;
reg   [31:0] mul_ln44_21_reg_3591;
wire   [31:0] grp_fu_1713_p2;
reg   [31:0] mul_ln44_reg_3596;
wire   [31:0] add_ln44_1_fu_2124_p2;
reg   [31:0] add_ln44_1_reg_3601;
reg   [31:0] add_ln44_1_reg_3601_pp0_iter2_reg;
reg   [31:0] add_ln44_1_reg_3601_pp0_iter3_reg;
wire   [31:0] sub_ln44_48_fu_2145_p2;
reg   [31:0] sub_ln44_48_reg_3606;
reg   [31:0] sub_ln44_48_reg_3606_pp0_iter2_reg;
wire   [31:0] add_ln44_133_fu_2160_p2;
reg   [31:0] add_ln44_133_reg_3611;
wire   [31:0] add_ln44_28_fu_2165_p2;
reg   [31:0] add_ln44_28_reg_3616;
wire   [31:0] add_ln44_31_fu_2176_p2;
reg   [31:0] add_ln44_31_reg_3621;
wire   [31:0] sub_ln44_55_fu_2197_p2;
reg   [31:0] sub_ln44_55_reg_3626;
wire   [31:0] add_ln44_42_fu_2203_p2;
reg   [31:0] add_ln44_42_reg_3631;
reg   [31:0] p_ZZ3firPiiE9shift_reg_125_load_reg_3636;
reg   [31:0] p_ZZ3firPiiE9shift_reg_121_load_reg_3642;
wire   [31:0] sub_ln44_1_fu_2403_p2;
reg   [31:0] sub_ln44_1_reg_3647;
wire   [31:0] grp_fu_1962_p2;
reg   [31:0] mul_ln44_2_reg_3652;
wire   [31:0] grp_fu_1997_p2;
reg   [31:0] mul_ln44_7_reg_3657;
wire   [31:0] sub_ln44_14_fu_2456_p2;
reg   [31:0] sub_ln44_14_reg_3662;
reg   [31:0] sub_ln44_14_reg_3662_pp0_iter3_reg;
wire   [31:0] sub_ln44_16_fu_2478_p2;
reg   [31:0] sub_ln44_16_reg_3667;
wire   [31:0] grp_fu_2012_p2;
reg   [31:0] mul_ln44_13_reg_3672;
wire   [31:0] add_ln44_81_fu_2489_p2;
reg   [31:0] add_ln44_81_reg_3677;
reg   [31:0] add_ln44_81_reg_3677_pp0_iter3_reg;
wire   [31:0] add_ln44_84_fu_2494_p2;
reg   [31:0] add_ln44_84_reg_3682;
wire   [31:0] sub_ln44_19_fu_2515_p2;
reg   [31:0] sub_ln44_19_reg_3687;
wire   [31:0] add_ln44_93_fu_2527_p2;
reg   [31:0] add_ln44_93_reg_3692;
wire   [31:0] add_ln44_95_fu_2533_p2;
reg   [31:0] add_ln44_95_reg_3697;
wire   [31:0] add_ln44_98_fu_2545_p2;
reg   [31:0] add_ln44_98_reg_3702;
wire   [31:0] add_ln44_102_fu_2557_p2;
reg   [31:0] add_ln44_102_reg_3707;
wire   [31:0] add_ln44_104_fu_2569_p2;
reg   [31:0] add_ln44_104_reg_3712;
wire   [31:0] add_ln44_111_fu_2586_p2;
reg   [31:0] add_ln44_111_reg_3717;
wire   [31:0] grp_fu_2034_p2;
reg   [31:0] mul_ln44_15_reg_3722;
wire   [31:0] grp_fu_2039_p2;
reg   [31:0] mul_ln44_20_reg_3727;
wire   [31:0] grp_fu_2053_p2;
reg   [31:0] mul_ln44_23_reg_3732;
wire   [31:0] add_ln44_76_fu_2612_p2;
reg   [31:0] add_ln44_76_reg_3737;
reg   [31:0] add_ln44_76_reg_3737_pp0_iter3_reg;
wire   [31:0] sub_ln44_46_fu_2658_p2;
reg   [31:0] sub_ln44_46_reg_3742;
reg   [31:0] sub_ln44_46_reg_3742_pp0_iter3_reg;
wire   [31:0] grp_fu_2151_p2;
reg   [31:0] mul_ln44_24_reg_3747;
wire   [31:0] add_ln44_134_fu_2668_p2;
reg   [31:0] add_ln44_134_reg_3752;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter3_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter4_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter5_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter6_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter7_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter8_reg;
reg   [31:0] add_ln44_134_reg_3752_pp0_iter9_reg;
wire   [31:0] add_ln44_32_fu_2678_p2;
reg   [31:0] add_ln44_32_reg_3758;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter3_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter4_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter5_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter6_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter7_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter8_reg;
reg   [31:0] add_ln44_32_reg_3758_pp0_iter9_reg;
wire   [31:0] add_ln44_35_fu_2688_p2;
reg   [31:0] add_ln44_35_reg_3763;
wire   [31:0] add_ln44_37_fu_2715_p2;
reg   [31:0] add_ln44_37_reg_3768;
wire   [31:0] add_ln44_44_fu_2724_p2;
reg   [31:0] add_ln44_44_reg_3773;
wire   [31:0] add_ln44_36_fu_2757_p2;
reg   [31:0] add_ln44_36_reg_3778;
wire   [31:0] add_ln44_82_fu_2767_p2;
reg   [31:0] add_ln44_82_reg_3783;
wire   [31:0] add_ln44_88_fu_2777_p2;
reg   [31:0] add_ln44_88_reg_3788;
wire   [31:0] add_ln44_94_fu_2787_p2;
reg   [31:0] add_ln44_94_reg_3793;
wire   [31:0] add_ln44_99_fu_2796_p2;
reg   [31:0] add_ln44_99_reg_3798;
wire   [31:0] add_ln44_112_fu_2805_p2;
reg   [31:0] add_ln44_112_reg_3803;
wire   [31:0] sub_ln44_27_fu_2836_p2;
reg   [31:0] sub_ln44_27_reg_3808;
wire   [31:0] add_ln44_60_fu_2846_p2;
reg   [31:0] add_ln44_60_reg_3813;
wire   [31:0] sub_ln44_30_fu_2867_p2;
reg   [31:0] sub_ln44_30_reg_3818;
wire   [31:0] add_ln44_72_fu_2878_p2;
reg   [31:0] add_ln44_72_reg_3823;
wire   [31:0] add_ln44_9_fu_2887_p2;
reg   [31:0] add_ln44_9_reg_3828;
wire   [31:0] add_ln44_45_fu_2896_p2;
reg   [31:0] add_ln44_45_reg_3833;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter4_reg;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter5_reg;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter6_reg;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter7_reg;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter8_reg;
reg   [31:0] add_ln44_45_reg_3833_pp0_iter9_reg;
wire   [31:0] add_ln44_40_fu_2905_p2;
reg   [31:0] add_ln44_40_reg_3838;
wire   [31:0] add_ln44_89_fu_2914_p2;
reg   [31:0] add_ln44_89_reg_3843;
wire   [31:0] add_ln44_113_fu_2923_p2;
reg   [31:0] add_ln44_113_reg_3848;
wire   [31:0] add_ln44_61_fu_2932_p2;
reg   [31:0] add_ln44_61_reg_3854;
reg   [31:0] add_ln44_61_reg_3854_pp0_iter5_reg;
reg   [31:0] add_ln44_61_reg_3854_pp0_iter6_reg;
wire   [31:0] add_ln44_78_fu_2941_p2;
reg   [31:0] add_ln44_78_reg_3859;
reg   [31:0] add_ln44_78_reg_3859_pp0_iter5_reg;
reg   [31:0] add_ln44_78_reg_3859_pp0_iter6_reg;
reg   [31:0] add_ln44_78_reg_3859_pp0_iter7_reg;
wire   [31:0] add_ln44_10_fu_2950_p2;
reg   [31:0] add_ln44_10_reg_3864;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter5_reg;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter6_reg;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter7_reg;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter8_reg;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter9_reg;
reg   [31:0] add_ln44_10_reg_3864_pp0_iter10_reg;
wire   [31:0] add_ln44_115_fu_2975_p2;
reg   [31:0] add_ln44_115_reg_3869;
wire   [31:0] add_ln44_50_fu_3018_p2;
reg   [31:0] add_ln44_50_reg_3874;
wire   [31:0] add_ln44_62_fu_3045_p2;
reg   [31:0] add_ln44_62_reg_3879;
wire   [31:0] add_ln44_23_fu_3070_p2;
reg   [31:0] add_ln44_23_reg_3884;
wire   [31:0] add_ln44_27_fu_3113_p2;
reg   [31:0] add_ln44_27_reg_3889;
wire   [31:0] sub_ln44_50_fu_3135_p2;
reg   [31:0] sub_ln44_50_reg_3894;
wire   [31:0] add_ln44_46_fu_3145_p2;
reg   [31:0] add_ln44_46_reg_3899;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] shl_ln44_2_fu_1293_p2;
wire   [31:0] shl_ln44_3_fu_1299_p2;
wire   [31:0] sub_ln44_2_fu_1305_p2;
wire   [31:0] shl_ln44_9_fu_1317_p2;
wire   [31:0] shl_ln44_10_fu_1323_p2;
wire   [31:0] sub_ln44_8_fu_1329_p2;
wire  signed [2:0] grp_fu_1341_p1;
wire  signed [4:0] grp_fu_1347_p1;
wire   [31:0] add_ln44_15_fu_1353_p2;
wire   [31:0] add_ln44_86_fu_1371_p2;
wire   [31:0] shl_ln44_24_fu_1383_p2;
wire   [31:0] shl_ln44_25_fu_1389_p2;
wire   [31:0] sub_ln44_20_fu_1395_p2;
wire   [31:0] shl_ln44_26_fu_1407_p2;
wire   [31:0] shl_ln44_27_fu_1413_p2;
wire   [31:0] sub_ln44_22_fu_1419_p2;
wire   [31:0] shl_ln44_29_fu_1431_p2;
wire  signed [2:0] grp_fu_1443_p1;
wire   [31:0] shl_ln44_33_fu_1449_p2;
wire   [31:0] shl_ln44_34_fu_1455_p2;
wire   [31:0] add_ln44_52_fu_1485_p2;
wire   [31:0] add_ln44_51_fu_1479_p2;
wire   [31:0] shl_ln44_37_fu_1467_p2;
wire   [31:0] sub_ln44_24_fu_1437_p2;
wire   [31:0] add_ln44_67_fu_1533_p2;
wire   [31:0] add_ln44_66_fu_1527_p2;
wire   [31:0] shl_ln44_46_fu_1551_p2;
wire   [31:0] sub_ln44_32_fu_1557_p2;
wire   [31:0] shl_ln44_47_fu_1563_p2;
wire   [31:0] shl_ln44_48_fu_1575_p2;
wire   [31:0] shl_ln44_49_fu_1581_p2;
wire   [31:0] sub_ln44_34_fu_1587_p2;
wire  signed [4:0] grp_fu_1599_p1;
wire  signed [4:0] grp_fu_1605_p1;
wire   [31:0] shl_ln44_55_fu_1611_p2;
wire   [31:0] shl_ln44_56_fu_1617_p2;
wire   [31:0] sub_ln44_38_fu_1623_p2;
wire   [31:0] shl_ln44_57_fu_1635_p2;
wire   [31:0] shl_ln44_58_fu_1641_p2;
wire   [31:0] sub_ln44_40_fu_1647_p2;
wire   [31:0] shl_ln44_59_fu_1659_p2;
wire   [31:0] shl_ln44_60_fu_1665_p2;
wire   [31:0] sub_ln44_42_fu_1671_p2;
wire  signed [2:0] grp_fu_1683_p1;
wire   [31:0] shl_ln44_69_fu_1689_p2;
wire   [31:0] sub_ln44_44_fu_1695_p2;
wire   [31:0] shl_ln44_70_fu_1701_p2;
wire  signed [2:0] grp_fu_1713_p1;
wire   [31:0] add_ln44_5_fu_1719_p2;
wire   [31:0] add_ln44_126_fu_1737_p2;
wire   [31:0] add_ln44_128_fu_1749_p2;
wire   [31:0] add_ln44_18_fu_1767_p2;
wire   [31:0] add_ln44_25_fu_1779_p2;
wire   [31:0] add_ln44_47_fu_1797_p2;
wire   [31:0] add_ln44_80_fu_1809_p2;
wire   [31:0] shl_ln44_84_fu_1815_p2;
wire   [31:0] sub_ln44_56_fu_1821_p2;
wire   [31:0] shl_ln44_85_fu_1827_p2;
wire   [31:0] shl_ln44_4_fu_1938_p2;
wire   [31:0] shl_ln44_5_fu_1944_p2;
wire   [31:0] sub_ln44_4_fu_1950_p2;
wire  signed [2:0] grp_fu_1962_p1;
wire   [31:0] shl_ln44_12_fu_1968_p2;
wire   [31:0] shl_ln44_13_fu_1974_p2;
wire   [31:0] sub_ln44_10_fu_1980_p2;
wire  signed [4:0] grp_fu_1997_p1;
wire   [31:0] shl_ln44_16_fu_1992_p2;
wire   [31:0] add_ln44_11_fu_2002_p2;
wire  signed [4:0] grp_fu_2012_p1;
wire   [31:0] add_ln44_109_fu_2023_p2;
wire   [31:0] add_ln44_108_fu_2017_p2;
wire  signed [2:0] grp_fu_2034_p1;
wire  signed [4:0] grp_fu_2039_p1;
wire   [31:0] add_ln44_65_fu_2044_p2;
wire  signed [4:0] grp_fu_2053_p1;
wire   [31:0] add_ln44_74_fu_2058_p2;
wire   [31:0] shl_ln44_50_fu_2067_p2;
wire   [31:0] shl_ln44_62_fu_2077_p2;
wire   [31:0] shl_ln44_63_fu_2082_p2;
wire   [31:0] shl_ln44_64_fu_2093_p2;
wire   [31:0] shl_ln44_65_fu_2098_p2;
wire   [31:0] shl_ln44_71_fu_2114_p2;
wire   [31:0] add_ln44_fu_2119_p2;
wire   [31:0] shl_ln44_74_fu_2129_p2;
wire   [31:0] sub_ln44_47_fu_2134_p2;
wire   [31:0] shl_ln44_75_fu_2140_p2;
wire  signed [4:0] grp_fu_2151_p1;
wire   [31:0] add_ln44_132_fu_2156_p2;
wire   [31:0] add_ln44_123_fu_2103_p2;
wire   [31:0] sub_ln44_36_fu_2072_p2;
wire   [31:0] shl_ln44_68_fu_2109_p2;
wire   [31:0] add_ln44_30_fu_2170_p2;
wire   [31:0] shl_ln44_82_fu_2181_p2;
wire   [31:0] sub_ln44_54_fu_2186_p2;
wire   [31:0] shl_ln44_83_fu_2192_p2;
wire   [31:0] add_ln44_122_fu_2087_p2;
wire   [31:0] shl_ln44_fu_2387_p2;
wire   [31:0] sub_ln44_fu_2392_p2;
wire   [31:0] shl_ln44_1_fu_2398_p2;
wire   [31:0] shl_ln44_8_fu_2414_p2;
wire   [31:0] shl_ln44_14_fu_2429_p2;
wire   [31:0] sub_ln44_12_fu_2434_p2;
wire   [31:0] shl_ln44_15_fu_2440_p2;
wire   [31:0] sub_ln44_7_fu_2419_p2;
wire   [31:0] add_ln44_13_fu_2451_p2;
wire   [31:0] shl_ln44_7_fu_2409_p2;
wire   [31:0] shl_ln44_18_fu_2462_p2;
wire   [31:0] sub_ln44_15_fu_2467_p2;
wire   [31:0] shl_ln44_19_fu_2473_p2;
wire   [31:0] shl_ln44_11_fu_2424_p2;
wire   [31:0] add_ln44_41_fu_2484_p2;
wire   [31:0] sub_ln44_13_fu_2445_p2;
wire   [31:0] shl_ln44_20_fu_2499_p2;
wire   [31:0] sub_ln44_18_fu_2504_p2;
wire   [31:0] shl_ln44_21_fu_2510_p2;
wire   [31:0] add_ln44_92_fu_2521_p2;
wire   [31:0] add_ln44_97_fu_2539_p2;
wire   [31:0] add_ln44_101_fu_2551_p2;
wire   [31:0] add_ln44_103_fu_2563_p2;
wire   [31:0] add_ln44_106_fu_2575_p2;
wire   [31:0] add_ln44_107_fu_2580_p2;
wire   [31:0] shl_ln44_30_fu_2596_p2;
wire   [31:0] sub_ln44_25_fu_2601_p2;
wire   [31:0] shl_ln44_28_fu_2591_p2;
wire   [31:0] add_ln44_73_fu_2606_p2;
wire   [31:0] shl_ln44_52_fu_2622_p2;
wire   [31:0] shl_ln44_53_fu_2632_p2;
wire   [31:0] shl_ln44_54_fu_2637_p2;
wire   [31:0] sub_ln44_37_fu_2627_p2;
wire   [31:0] add_ln44_2_fu_2653_p2;
wire   [31:0] shl_ln44_51_fu_2617_p2;
wire   [31:0] add_ln44_130_fu_2664_p2;
wire   [31:0] add_ln44_121_fu_2642_p2;
wire   [31:0] add_ln44_29_fu_2673_p2;
wire   [31:0] shl_ln44_61_fu_2648_p2;
wire   [31:0] sub_ln44_51_fu_2683_p2;
wire   [31:0] shl_ln44_80_fu_2693_p2;
wire   [31:0] sub_ln44_52_fu_2698_p2;
wire   [31:0] shl_ln44_81_fu_2704_p2;
wire   [31:0] sub_ln44_53_fu_2709_p2;
wire   [31:0] add_ln44_43_fu_2720_p2;
wire   [31:0] shl_ln44_6_fu_2738_p2;
wire   [31:0] add_ln44_20_fu_2753_p2;
wire   [31:0] shl_ln44_17_fu_2748_p2;
wire   [31:0] sub_ln44_17_fu_2762_p2;
wire   [31:0] sub_ln44_6_fu_2743_p2;
wire   [31:0] add_ln44_85_fu_2773_p2;
wire   [31:0] add_ln44_91_fu_2782_p2;
wire   [31:0] add_ln44_96_fu_2792_p2;
wire   [31:0] add_ln44_105_fu_2801_p2;
wire   [31:0] shl_ln44_42_fu_2820_p2;
wire   [31:0] shl_ln44_43_fu_2825_p2;
wire   [31:0] sub_ln44_26_fu_2830_p2;
wire   [31:0] shl_ln44_32_fu_2815_p2;
wire   [31:0] sub_ln44_28_fu_2841_p2;
wire   [31:0] shl_ln44_44_fu_2851_p2;
wire   [31:0] sub_ln44_29_fu_2856_p2;
wire   [31:0] shl_ln44_45_fu_2862_p2;
wire   [31:0] shl_ln44_31_fu_2810_p2;
wire   [31:0] sub_ln44_31_fu_2873_p2;
wire   [31:0] add_ln44_8_fu_2883_p2;
wire   [31:0] add_ln44_38_fu_2892_p2;
wire   [31:0] add_ln44_14_fu_2901_p2;
wire   [31:0] add_ln44_83_fu_2910_p2;
wire   [31:0] add_ln44_100_fu_2919_p2;
wire   [31:0] add_ln44_57_fu_2928_p2;
wire   [31:0] add_ln44_77_fu_2937_p2;
wire   [31:0] add_ln44_4_fu_2946_p2;
wire   [31:0] shl_ln44_22_fu_2959_p2;
wire   [31:0] shl_ln44_23_fu_2964_p2;
wire   [31:0] add_ln44_114_fu_2969_p2;
wire   [31:0] add_ln44_90_fu_2955_p2;
wire   [31:0] shl_ln44_35_fu_2981_p2;
wire   [31:0] shl_ln44_36_fu_2986_p2;
wire   [31:0] add_ln44_117_fu_2991_p2;
wire   [31:0] shl_ln44_38_fu_3002_p2;
wire   [31:0] shl_ln44_39_fu_3007_p2;
wire   [31:0] add_ln44_118_fu_3012_p2;
wire   [31:0] add_ln44_48_fu_2997_p2;
wire   [31:0] shl_ln44_40_fu_3024_p2;
wire   [31:0] shl_ln44_41_fu_3029_p2;
wire   [31:0] add_ln44_119_fu_3034_p2;
wire   [31:0] add_ln44_54_fu_3040_p2;
wire   [31:0] shl_ln44_72_fu_3054_p2;
wire   [31:0] shl_ln44_73_fu_3059_p2;
wire   [31:0] add_ln44_125_fu_3064_p2;
wire   [31:0] acc_fu_3050_p2;
wire   [31:0] shl_ln44_66_fu_3076_p2;
wire   [31:0] shl_ln44_67_fu_3081_p2;
wire   [31:0] add_ln44_124_fu_3086_p2;
wire   [31:0] shl_ln44_78_fu_3097_p2;
wire   [31:0] shl_ln44_79_fu_3102_p2;
wire   [31:0] add_ln44_135_fu_3107_p2;
wire   [31:0] add_ln44_24_fu_3092_p2;
wire   [31:0] shl_ln44_76_fu_3119_p2;
wire   [31:0] sub_ln44_49_fu_3124_p2;
wire   [31:0] shl_ln44_77_fu_3130_p2;
wire   [31:0] add_ln44_33_fu_3141_p2;
wire   [31:0] add_ln44_22_fu_3150_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to10;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 p_ZZ3firPiiE9shift_reg_126 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_125 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_124 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_123 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_122 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_121 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_120 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_119 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_118 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_117 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_116 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_115 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_114 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_113 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_112 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_111 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_110 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_109 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_108 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_107 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_106 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_105 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_104 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_103 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_102 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_101 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_100 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_99 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_98 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_97 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_96 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_95 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_94 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_93 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_92 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_91 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_90 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_89 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_88 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_87 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_86 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_85 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_84 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_83 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_82 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_81 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_80 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_79 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_78 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_77 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_76 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_75 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_74 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_73 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_72 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_71 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_70 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_69 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_68 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_67 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_66 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_65 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_64 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_63 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_62 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_61 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_60 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_59 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_58 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_57 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_56 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_55 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_54 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_53 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_52 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_51 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_50 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_49 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_48 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_47 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_46 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_45 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_44 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_43 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_42 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_41 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_40 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_39 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_38 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_37 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_36 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_35 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_34 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_33 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_32 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_31 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_30 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_29 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_28 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_27 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_26 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_25 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_24 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_23 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_22 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_21 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_20 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_19 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_18 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_17 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_16 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_15 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_14 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_13 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_12 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_11 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_10 = 32'd0;
#0 fir_int_int_shift_reg_9 = 32'd0;
#0 fir_int_int_shift_reg_8 = 32'd0;
#0 fir_int_int_shift_reg_7 = 32'd0;
#0 fir_int_int_shift_reg_6 = 32'd0;
#0 fir_int_int_shift_reg_5 = 32'd0;
#0 fir_int_int_shift_reg_4 = 32'd0;
#0 fir_int_int_shift_reg_3 = 32'd0;
#0 fir_int_int_shift_reg_2 = 32'd0;
#0 fir_int_int_shift_reg_1 = 32'd0;
#0 fir_int_int_shift_reg = 32'd0;
end

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_84),
    .din1(grp_fu_1341_p1),
    .ce(1'b1),
    .dout(grp_fu_1341_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_96),
    .din1(grp_fu_1347_p1),
    .ce(1'b1),
    .dout(grp_fu_1347_p2)
);

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_52),
    .din1(grp_fu_1443_p1),
    .ce(1'b1),
    .dout(grp_fu_1443_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_32),
    .din1(grp_fu_1599_p1),
    .ce(1'b1),
    .dout(grp_fu_1599_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_33),
    .din1(grp_fu_1605_p1),
    .ce(1'b1),
    .dout(grp_fu_1605_p2)
);

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_35),
    .din1(grp_fu_1683_p1),
    .ce(1'b1),
    .dout(grp_fu_1683_p2)
);

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fir_int_int_shift_reg_4),
    .din1(grp_fu_1713_p1),
    .ce(1'b1),
    .dout(grp_fu_1713_p2)
);

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_99),
    .din1(grp_fu_1962_p1),
    .ce(1'b1),
    .dout(grp_fu_1962_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_97_load_reg_3166),
    .din1(grp_fu_1997_p1),
    .ce(1'b1),
    .dout(grp_fu_1997_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln44_17_reg_3349),
    .din1(grp_fu_2012_p1),
    .ce(1'b1),
    .dout(grp_fu_2012_p2)
);

fir_mul_32s_3s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mul_32s_3s_32_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZZ3firPiiE9shift_reg_67_load_reg_3221),
    .din1(grp_fu_2034_p1),
    .ce(1'b1),
    .dout(grp_fu_2034_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln44_59_reg_3399),
    .din1(grp_fu_2039_p1),
    .ce(1'b1),
    .dout(grp_fu_2039_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln44_70_reg_3419),
    .din1(grp_fu_2053_p1),
    .ce(1'b1),
    .dout(grp_fu_2053_p2)
);

fir_mul_32s_5s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mul_32s_5s_32_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln44_7_reg_3460),
    .din1(grp_fu_2151_p1),
    .ce(1'b1),
    .dout(grp_fu_2151_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln44_102_reg_3707 <= add_ln44_102_fu_2557_p2;
        add_ln44_104_reg_3712 <= add_ln44_104_fu_2569_p2;
        add_ln44_10_reg_3864 <= add_ln44_10_fu_2950_p2;
        add_ln44_10_reg_3864_pp0_iter10_reg <= add_ln44_10_reg_3864_pp0_iter9_reg;
        add_ln44_10_reg_3864_pp0_iter5_reg <= add_ln44_10_reg_3864;
        add_ln44_10_reg_3864_pp0_iter6_reg <= add_ln44_10_reg_3864_pp0_iter5_reg;
        add_ln44_10_reg_3864_pp0_iter7_reg <= add_ln44_10_reg_3864_pp0_iter6_reg;
        add_ln44_10_reg_3864_pp0_iter8_reg <= add_ln44_10_reg_3864_pp0_iter7_reg;
        add_ln44_10_reg_3864_pp0_iter9_reg <= add_ln44_10_reg_3864_pp0_iter8_reg;
        add_ln44_111_reg_3717 <= add_ln44_111_fu_2586_p2;
        add_ln44_112_reg_3803 <= add_ln44_112_fu_2805_p2;
        add_ln44_113_reg_3848 <= add_ln44_113_fu_2923_p2;
        add_ln44_115_reg_3869 <= add_ln44_115_fu_2975_p2;
        add_ln44_12_reg_3555_pp0_iter2_reg <= add_ln44_12_reg_3555;
        add_ln44_12_reg_3555_pp0_iter3_reg <= add_ln44_12_reg_3555_pp0_iter2_reg;
        add_ln44_134_reg_3752 <= add_ln44_134_fu_2668_p2;
        add_ln44_134_reg_3752_pp0_iter3_reg <= add_ln44_134_reg_3752;
        add_ln44_134_reg_3752_pp0_iter4_reg <= add_ln44_134_reg_3752_pp0_iter3_reg;
        add_ln44_134_reg_3752_pp0_iter5_reg <= add_ln44_134_reg_3752_pp0_iter4_reg;
        add_ln44_134_reg_3752_pp0_iter6_reg <= add_ln44_134_reg_3752_pp0_iter5_reg;
        add_ln44_134_reg_3752_pp0_iter7_reg <= add_ln44_134_reg_3752_pp0_iter6_reg;
        add_ln44_134_reg_3752_pp0_iter8_reg <= add_ln44_134_reg_3752_pp0_iter7_reg;
        add_ln44_134_reg_3752_pp0_iter9_reg <= add_ln44_134_reg_3752_pp0_iter8_reg;
        add_ln44_1_reg_3601_pp0_iter2_reg <= add_ln44_1_reg_3601;
        add_ln44_1_reg_3601_pp0_iter3_reg <= add_ln44_1_reg_3601_pp0_iter2_reg;
        add_ln44_23_reg_3884 <= add_ln44_23_fu_3070_p2;
        add_ln44_26_reg_3485_pp0_iter2_reg <= add_ln44_26_reg_3485_pp0_iter1_reg;
        add_ln44_26_reg_3485_pp0_iter3_reg <= add_ln44_26_reg_3485_pp0_iter2_reg;
        add_ln44_26_reg_3485_pp0_iter4_reg <= add_ln44_26_reg_3485_pp0_iter3_reg;
        add_ln44_26_reg_3485_pp0_iter5_reg <= add_ln44_26_reg_3485_pp0_iter4_reg;
        add_ln44_26_reg_3485_pp0_iter6_reg <= add_ln44_26_reg_3485_pp0_iter5_reg;
        add_ln44_26_reg_3485_pp0_iter7_reg <= add_ln44_26_reg_3485_pp0_iter6_reg;
        add_ln44_26_reg_3485_pp0_iter8_reg <= add_ln44_26_reg_3485_pp0_iter7_reg;
        add_ln44_27_reg_3889 <= add_ln44_27_fu_3113_p2;
        add_ln44_32_reg_3758 <= add_ln44_32_fu_2678_p2;
        add_ln44_32_reg_3758_pp0_iter3_reg <= add_ln44_32_reg_3758;
        add_ln44_32_reg_3758_pp0_iter4_reg <= add_ln44_32_reg_3758_pp0_iter3_reg;
        add_ln44_32_reg_3758_pp0_iter5_reg <= add_ln44_32_reg_3758_pp0_iter4_reg;
        add_ln44_32_reg_3758_pp0_iter6_reg <= add_ln44_32_reg_3758_pp0_iter5_reg;
        add_ln44_32_reg_3758_pp0_iter7_reg <= add_ln44_32_reg_3758_pp0_iter6_reg;
        add_ln44_32_reg_3758_pp0_iter8_reg <= add_ln44_32_reg_3758_pp0_iter7_reg;
        add_ln44_32_reg_3758_pp0_iter9_reg <= add_ln44_32_reg_3758_pp0_iter8_reg;
        add_ln44_35_reg_3763 <= add_ln44_35_fu_2688_p2;
        add_ln44_36_reg_3778 <= add_ln44_36_fu_2757_p2;
        add_ln44_37_reg_3768 <= add_ln44_37_fu_2715_p2;
        add_ln44_40_reg_3838 <= add_ln44_40_fu_2905_p2;
        add_ln44_44_reg_3773 <= add_ln44_44_fu_2724_p2;
        add_ln44_45_reg_3833 <= add_ln44_45_fu_2896_p2;
        add_ln44_45_reg_3833_pp0_iter4_reg <= add_ln44_45_reg_3833;
        add_ln44_45_reg_3833_pp0_iter5_reg <= add_ln44_45_reg_3833_pp0_iter4_reg;
        add_ln44_45_reg_3833_pp0_iter6_reg <= add_ln44_45_reg_3833_pp0_iter5_reg;
        add_ln44_45_reg_3833_pp0_iter7_reg <= add_ln44_45_reg_3833_pp0_iter6_reg;
        add_ln44_45_reg_3833_pp0_iter8_reg <= add_ln44_45_reg_3833_pp0_iter7_reg;
        add_ln44_45_reg_3833_pp0_iter9_reg <= add_ln44_45_reg_3833_pp0_iter8_reg;
        add_ln44_46_reg_3899 <= add_ln44_46_fu_3145_p2;
        add_ln44_49_reg_3375_pp0_iter2_reg <= add_ln44_49_reg_3375_pp0_iter1_reg;
        add_ln44_49_reg_3375_pp0_iter3_reg <= add_ln44_49_reg_3375_pp0_iter2_reg;
        add_ln44_49_reg_3375_pp0_iter4_reg <= add_ln44_49_reg_3375_pp0_iter3_reg;
        add_ln44_49_reg_3375_pp0_iter5_reg <= add_ln44_49_reg_3375_pp0_iter4_reg;
        add_ln44_50_reg_3874 <= add_ln44_50_fu_3018_p2;
        add_ln44_53_reg_3381_pp0_iter2_reg <= add_ln44_53_reg_3381_pp0_iter1_reg;
        add_ln44_53_reg_3381_pp0_iter3_reg <= add_ln44_53_reg_3381_pp0_iter2_reg;
        add_ln44_53_reg_3381_pp0_iter4_reg <= add_ln44_53_reg_3381_pp0_iter3_reg;
        add_ln44_53_reg_3381_pp0_iter5_reg <= add_ln44_53_reg_3381_pp0_iter4_reg;
        add_ln44_53_reg_3381_pp0_iter6_reg <= add_ln44_53_reg_3381_pp0_iter5_reg;
        add_ln44_55_reg_3387_pp0_iter2_reg <= add_ln44_55_reg_3387_pp0_iter1_reg;
        add_ln44_56_reg_3394_pp0_iter2_reg <= add_ln44_56_reg_3394_pp0_iter1_reg;
        add_ln44_56_reg_3394_pp0_iter3_reg <= add_ln44_56_reg_3394_pp0_iter2_reg;
        add_ln44_60_reg_3813 <= add_ln44_60_fu_2846_p2;
        add_ln44_61_reg_3854 <= add_ln44_61_fu_2932_p2;
        add_ln44_61_reg_3854_pp0_iter5_reg <= add_ln44_61_reg_3854;
        add_ln44_61_reg_3854_pp0_iter6_reg <= add_ln44_61_reg_3854_pp0_iter5_reg;
        add_ln44_62_reg_3879 <= add_ln44_62_fu_3045_p2;
        add_ln44_69_reg_3570_pp0_iter2_reg <= add_ln44_69_reg_3570;
        add_ln44_72_reg_3823 <= add_ln44_72_fu_2878_p2;
        add_ln44_76_reg_3737 <= add_ln44_76_fu_2612_p2;
        add_ln44_76_reg_3737_pp0_iter3_reg <= add_ln44_76_reg_3737;
        add_ln44_78_reg_3859 <= add_ln44_78_fu_2941_p2;
        add_ln44_78_reg_3859_pp0_iter5_reg <= add_ln44_78_reg_3859;
        add_ln44_78_reg_3859_pp0_iter6_reg <= add_ln44_78_reg_3859_pp0_iter5_reg;
        add_ln44_78_reg_3859_pp0_iter7_reg <= add_ln44_78_reg_3859_pp0_iter6_reg;
        add_ln44_81_reg_3677 <= add_ln44_81_fu_2489_p2;
        add_ln44_81_reg_3677_pp0_iter3_reg <= add_ln44_81_reg_3677;
        add_ln44_82_reg_3783 <= add_ln44_82_fu_2767_p2;
        add_ln44_84_reg_3682 <= add_ln44_84_fu_2494_p2;
        add_ln44_88_reg_3788 <= add_ln44_88_fu_2777_p2;
        add_ln44_89_reg_3843 <= add_ln44_89_fu_2914_p2;
        add_ln44_93_reg_3692 <= add_ln44_93_fu_2527_p2;
        add_ln44_94_reg_3793 <= add_ln44_94_fu_2787_p2;
        add_ln44_95_reg_3697 <= add_ln44_95_fu_2533_p2;
        add_ln44_98_reg_3702 <= add_ln44_98_fu_2545_p2;
        add_ln44_99_reg_3798 <= add_ln44_99_fu_2796_p2;
        add_ln44_9_reg_3828 <= add_ln44_9_fu_2887_p2;
        fir_int_int_shift_reg_26_reg_3231_pp0_iter2_reg <= fir_int_int_shift_reg_26_reg_3231_pp0_iter1_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter2_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter1_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter3_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter2_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter4_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter3_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter5_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter4_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter6_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter5_reg;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter7_reg <= fir_int_int_shift_reg_29_reg_3258_pp0_iter6_reg;
        mul_ln44_13_reg_3672 <= grp_fu_2012_p2;
        mul_ln44_15_reg_3722 <= grp_fu_2034_p2;
        mul_ln44_19_reg_3565_pp0_iter2_reg <= mul_ln44_19_reg_3565;
        mul_ln44_20_reg_3727 <= grp_fu_2039_p2;
        mul_ln44_23_reg_3732 <= grp_fu_2053_p2;
        mul_ln44_24_reg_3747 <= grp_fu_2151_p2;
        mul_ln44_2_reg_3652 <= grp_fu_1962_p2;
        mul_ln44_7_reg_3657 <= grp_fu_1997_p2;
        p_ZZ3firPiiE9shift_reg_100_load_reg_3519_pp0_iter2_reg <= p_ZZ3firPiiE9shift_reg_100_load_reg_3519;
        p_ZZ3firPiiE9shift_reg_121_load_reg_3642 <= p_ZZ3firPiiE9shift_reg_121;
        p_ZZ3firPiiE9shift_reg_125_load_reg_3636 <= p_ZZ3firPiiE9shift_reg_125;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter2_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter1_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter3_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter2_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter4_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter3_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter5_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter4_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter6_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter5_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter7_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter6_reg;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter8_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter7_reg;
        p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter2_reg <= p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter1_reg;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter2_reg <= p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter1_reg;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter3_reg <= p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter2_reg;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter4_reg <= p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter3_reg;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter5_reg <= p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter4_reg;
        p_ZZ3firPiiE9shift_reg_98_load_reg_3530_pp0_iter2_reg <= p_ZZ3firPiiE9shift_reg_98_load_reg_3530;
        sub_ln44_14_reg_3662 <= sub_ln44_14_fu_2456_p2;
        sub_ln44_14_reg_3662_pp0_iter3_reg <= sub_ln44_14_reg_3662;
        sub_ln44_16_reg_3667 <= sub_ln44_16_fu_2478_p2;
        sub_ln44_19_reg_3687 <= sub_ln44_19_fu_2515_p2;
        sub_ln44_1_reg_3647 <= sub_ln44_1_fu_2403_p2;
        sub_ln44_27_reg_3808 <= sub_ln44_27_fu_2836_p2;
        sub_ln44_30_reg_3818 <= sub_ln44_30_fu_2867_p2;
        sub_ln44_33_reg_3424_pp0_iter2_reg <= sub_ln44_33_reg_3424_pp0_iter1_reg;
        sub_ln44_46_reg_3742 <= sub_ln44_46_fu_2658_p2;
        sub_ln44_46_reg_3742_pp0_iter3_reg <= sub_ln44_46_reg_3742;
        sub_ln44_48_reg_3606_pp0_iter2_reg <= sub_ln44_48_reg_3606;
        sub_ln44_50_reg_3894 <= sub_ln44_50_fu_3135_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln44_110_reg_3560 <= add_ln44_110_fu_2028_p2;
        add_ln44_116_reg_3370 <= add_ln44_116_fu_1461_p2;
        add_ln44_127_reg_3465 <= add_ln44_127_fu_1743_p2;
        add_ln44_127_reg_3465_pp0_iter1_reg <= add_ln44_127_reg_3465;
        add_ln44_129_reg_3470 <= add_ln44_129_fu_1755_p2;
        add_ln44_129_reg_3470_pp0_iter1_reg <= add_ln44_129_reg_3470;
        add_ln44_12_reg_3555 <= add_ln44_12_fu_2007_p2;
        add_ln44_131_reg_3475 <= add_ln44_131_fu_1761_p2;
        add_ln44_133_reg_3611 <= add_ln44_133_fu_2160_p2;
        add_ln44_16_reg_3343 <= add_ln44_16_fu_1359_p2;
        add_ln44_16_reg_3343_pp0_iter1_reg <= add_ln44_16_reg_3343;
        add_ln44_17_reg_3349 <= add_ln44_17_fu_1365_p2;
        add_ln44_19_reg_3480 <= add_ln44_19_fu_1773_p2;
        add_ln44_1_reg_3601 <= add_ln44_1_fu_2124_p2;
        add_ln44_26_reg_3485 <= add_ln44_26_fu_1785_p2;
        add_ln44_26_reg_3485_pp0_iter1_reg <= add_ln44_26_reg_3485;
        add_ln44_28_reg_3616 <= add_ln44_28_fu_2165_p2;
        add_ln44_31_reg_3621 <= add_ln44_31_fu_2176_p2;
        add_ln44_39_reg_3491 <= add_ln44_39_fu_1791_p2;
        add_ln44_39_reg_3491_pp0_iter1_reg <= add_ln44_39_reg_3491;
        add_ln44_42_reg_3631 <= add_ln44_42_fu_2203_p2;
        add_ln44_49_reg_3375 <= add_ln44_49_fu_1473_p2;
        add_ln44_49_reg_3375_pp0_iter1_reg <= add_ln44_49_reg_3375;
        add_ln44_53_reg_3381 <= add_ln44_53_fu_1491_p2;
        add_ln44_53_reg_3381_pp0_iter1_reg <= add_ln44_53_reg_3381;
        add_ln44_55_reg_3387 <= add_ln44_55_fu_1497_p2;
        add_ln44_55_reg_3387_pp0_iter1_reg <= add_ln44_55_reg_3387;
        add_ln44_56_reg_3394 <= add_ln44_56_fu_1503_p2;
        add_ln44_56_reg_3394_pp0_iter1_reg <= add_ln44_56_reg_3394;
        add_ln44_59_reg_3399 <= add_ln44_59_fu_1509_p2;
        add_ln44_63_reg_3404 <= add_ln44_63_fu_1515_p2;
        add_ln44_64_reg_3409 <= add_ln44_64_fu_1521_p2;
        add_ln44_68_reg_3414 <= add_ln44_68_fu_1539_p2;
        add_ln44_69_reg_3570 <= add_ln44_69_fu_2048_p2;
        add_ln44_6_reg_3454 <= add_ln44_6_fu_1725_p2;
        add_ln44_70_reg_3419 <= add_ln44_70_fu_1545_p2;
        add_ln44_75_reg_3576 <= add_ln44_75_fu_2062_p2;
        add_ln44_79_reg_3497 <= add_ln44_79_fu_1803_p2;
        add_ln44_7_reg_3460 <= add_ln44_7_fu_1731_p2;
        add_ln44_87_reg_3354 <= add_ln44_87_fu_1377_p2;
        add_ln44_87_reg_3354_pp0_iter1_reg <= add_ln44_87_reg_3354;
        fir_int_int_shift_reg_11_reg_3199 <= p_ZZ3firPiiE9shift_reg_83;
        fir_int_int_shift_reg_11_reg_3199_pp0_iter1_reg <= fir_int_int_shift_reg_11_reg_3199;
        fir_int_int_shift_reg_12_reg_3205 <= p_ZZ3firPiiE9shift_reg_82;
        fir_int_int_shift_reg_26_reg_3231 <= p_ZZ3firPiiE9shift_reg_53;
        fir_int_int_shift_reg_26_reg_3231_pp0_iter1_reg <= fir_int_int_shift_reg_26_reg_3231;
        fir_int_int_shift_reg_28_reg_3241 <= p_ZZ3firPiiE9shift_reg_51;
        fir_int_int_shift_reg_28_reg_3241_pp0_iter1_reg <= fir_int_int_shift_reg_28_reg_3241;
        fir_int_int_shift_reg_29_reg_3258 <= p_ZZ3firPiiE9shift_reg_45;
        fir_int_int_shift_reg_29_reg_3258_pp0_iter1_reg <= fir_int_int_shift_reg_29_reg_3258;
        fir_int_int_shift_reg_2_load_reg_3328 <= fir_int_int_shift_reg_2;
        fir_int_int_shift_reg_33_reg_3264 <= p_ZZ3firPiiE9shift_reg_41;
        fir_int_int_shift_reg_33_reg_3264_pp0_iter1_reg <= fir_int_int_shift_reg_33_reg_3264;
        fir_int_int_shift_reg_35_reg_3292 <= p_ZZ3firPiiE9shift_reg_34;
        fir_int_int_shift_reg_35_reg_3292_pp0_iter1_reg <= fir_int_int_shift_reg_35_reg_3292;
        fir_int_int_shift_reg_3_load_reg_3322 <= fir_int_int_shift_reg_3;
        fir_int_int_shift_reg_3_load_reg_3322_pp0_iter1_reg <= fir_int_int_shift_reg_3_load_reg_3322;
        fir_int_int_shift_reg_5_load_reg_3312 <= fir_int_int_shift_reg_5;
        fir_int_int_shift_reg_5_load_reg_3312_pp0_iter1_reg <= fir_int_int_shift_reg_5_load_reg_3312;
        fir_int_int_shift_reg_9_reg_3189 <= p_ZZ3firPiiE9shift_reg_85;
        fir_int_int_shift_reg_9_reg_3189_pp0_iter1_reg <= fir_int_int_shift_reg_9_reg_3189;
        fir_int_int_shift_reg_reg_3177 <= p_ZZ3firPiiE9shift_reg_95;
        fir_int_int_shift_reg_reg_3177_pp0_iter1_reg <= fir_int_int_shift_reg_reg_3177;
        mul_ln44_19_reg_3565 <= grp_fu_1443_p2;
        mul_ln44_21_reg_3591 <= grp_fu_1683_p2;
        mul_ln44_4_reg_3545 <= grp_fu_1341_p2;
        mul_ln44_5_reg_3581 <= grp_fu_1599_p2;
        mul_ln44_6_reg_3550 <= grp_fu_1347_p2;
        mul_ln44_9_reg_3586 <= grp_fu_1605_p2;
        mul_ln44_reg_3596 <= grp_fu_1713_p2;
        p_ZZ3firPiiE9shift_reg_100_load_reg_3519 <= p_ZZ3firPiiE9shift_reg_100;
        p_ZZ3firPiiE9shift_reg_101_load_reg_3514 <= p_ZZ3firPiiE9shift_reg_101;
        p_ZZ3firPiiE9shift_reg_107_load_reg_3508 <= p_ZZ3firPiiE9shift_reg_107;
        p_ZZ3firPiiE9shift_reg_17_load_reg_3307 <= p_ZZ3firPiiE9shift_reg_17;
        p_ZZ3firPiiE9shift_reg_36_load_reg_3281 <= p_ZZ3firPiiE9shift_reg_36;
        p_ZZ3firPiiE9shift_reg_37_load_reg_3276 <= p_ZZ3firPiiE9shift_reg_37;
        p_ZZ3firPiiE9shift_reg_40_load_reg_3270 <= p_ZZ3firPiiE9shift_reg_40;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252 <= p_ZZ3firPiiE9shift_reg_46;
        p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter1_reg <= p_ZZ3firPiiE9shift_reg_46_load_reg_3252;
        p_ZZ3firPiiE9shift_reg_50_load_reg_3247 <= p_ZZ3firPiiE9shift_reg_50;
        p_ZZ3firPiiE9shift_reg_50_load_reg_3247_pp0_iter1_reg <= p_ZZ3firPiiE9shift_reg_50_load_reg_3247;
        p_ZZ3firPiiE9shift_reg_66_load_reg_3226 <= p_ZZ3firPiiE9shift_reg_66;
        p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter1_reg <= p_ZZ3firPiiE9shift_reg_66_load_reg_3226;
        p_ZZ3firPiiE9shift_reg_67_load_reg_3221 <= p_ZZ3firPiiE9shift_reg_67;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215 <= p_ZZ3firPiiE9shift_reg_78;
        p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter1_reg <= p_ZZ3firPiiE9shift_reg_78_load_reg_3215;
        p_ZZ3firPiiE9shift_reg_79_load_reg_3210 <= p_ZZ3firPiiE9shift_reg_79;
        p_ZZ3firPiiE9shift_reg_88_load_reg_3183 <= p_ZZ3firPiiE9shift_reg_88;
        p_ZZ3firPiiE9shift_reg_88_load_reg_3183_pp0_iter1_reg <= p_ZZ3firPiiE9shift_reg_88_load_reg_3183;
        p_ZZ3firPiiE9shift_reg_97_load_reg_3166 <= p_ZZ3firPiiE9shift_reg_97;
        p_ZZ3firPiiE9shift_reg_98_load_reg_3530 <= p_ZZ3firPiiE9shift_reg_98;
        sub_ln44_11_reg_3540 <= sub_ln44_11_fu_1986_p2;
        sub_ln44_21_reg_3360 <= sub_ln44_21_fu_1401_p2;
        sub_ln44_23_reg_3365 <= sub_ln44_23_fu_1425_p2;
        sub_ln44_33_reg_3424 <= sub_ln44_33_fu_1569_p2;
        sub_ln44_33_reg_3424_pp0_iter1_reg <= sub_ln44_33_reg_3424;
        sub_ln44_35_reg_3429 <= sub_ln44_35_fu_1593_p2;
        sub_ln44_39_reg_3434 <= sub_ln44_39_fu_1629_p2;
        sub_ln44_3_reg_3333 <= sub_ln44_3_fu_1311_p2;
        sub_ln44_41_reg_3439 <= sub_ln44_41_fu_1653_p2;
        sub_ln44_43_reg_3444 <= sub_ln44_43_fu_1677_p2;
        sub_ln44_45_reg_3449 <= sub_ln44_45_fu_1707_p2;
        sub_ln44_48_reg_3606 <= sub_ln44_48_fu_2145_p2;
        sub_ln44_55_reg_3626 <= sub_ln44_55_fu_2197_p2;
        sub_ln44_57_reg_3503 <= sub_ln44_57_fu_1833_p2;
        sub_ln44_57_reg_3503_pp0_iter1_reg <= sub_ln44_57_reg_3503;
        sub_ln44_5_reg_3535 <= sub_ln44_5_fu_1956_p2;
        sub_ln44_9_reg_3338 <= sub_ln44_9_fu_1335_p2;
        x_read_reg_3160 <= x;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fir_int_int_shift_reg <= x;
        fir_int_int_shift_reg_1 <= fir_int_int_shift_reg;
        fir_int_int_shift_reg_2 <= fir_int_int_shift_reg_1;
        fir_int_int_shift_reg_3 <= fir_int_int_shift_reg_2;
        fir_int_int_shift_reg_4 <= fir_int_int_shift_reg_3;
        fir_int_int_shift_reg_5 <= fir_int_int_shift_reg_4;
        fir_int_int_shift_reg_6 <= fir_int_int_shift_reg_5;
        fir_int_int_shift_reg_7 <= fir_int_int_shift_reg_6;
        fir_int_int_shift_reg_8 <= fir_int_int_shift_reg_7;
        fir_int_int_shift_reg_9 <= fir_int_int_shift_reg_8;
        p_ZZ3firPiiE9shift_reg_10 <= fir_int_int_shift_reg_9;
        p_ZZ3firPiiE9shift_reg_11 <= p_ZZ3firPiiE9shift_reg_10;
        p_ZZ3firPiiE9shift_reg_12 <= p_ZZ3firPiiE9shift_reg_11;
        p_ZZ3firPiiE9shift_reg_13 <= p_ZZ3firPiiE9shift_reg_12;
        p_ZZ3firPiiE9shift_reg_14 <= p_ZZ3firPiiE9shift_reg_13;
        p_ZZ3firPiiE9shift_reg_15 <= p_ZZ3firPiiE9shift_reg_14;
        p_ZZ3firPiiE9shift_reg_16 <= p_ZZ3firPiiE9shift_reg_15;
        p_ZZ3firPiiE9shift_reg_17 <= p_ZZ3firPiiE9shift_reg_16;
        p_ZZ3firPiiE9shift_reg_18 <= p_ZZ3firPiiE9shift_reg_17;
        p_ZZ3firPiiE9shift_reg_19 <= p_ZZ3firPiiE9shift_reg_18;
        p_ZZ3firPiiE9shift_reg_20 <= p_ZZ3firPiiE9shift_reg_19;
        p_ZZ3firPiiE9shift_reg_21 <= p_ZZ3firPiiE9shift_reg_20;
        p_ZZ3firPiiE9shift_reg_22 <= p_ZZ3firPiiE9shift_reg_21;
        p_ZZ3firPiiE9shift_reg_23 <= p_ZZ3firPiiE9shift_reg_22;
        p_ZZ3firPiiE9shift_reg_24 <= p_ZZ3firPiiE9shift_reg_23;
        p_ZZ3firPiiE9shift_reg_25 <= p_ZZ3firPiiE9shift_reg_24;
        p_ZZ3firPiiE9shift_reg_26 <= p_ZZ3firPiiE9shift_reg_25;
        p_ZZ3firPiiE9shift_reg_27 <= p_ZZ3firPiiE9shift_reg_26;
        p_ZZ3firPiiE9shift_reg_28 <= p_ZZ3firPiiE9shift_reg_27;
        p_ZZ3firPiiE9shift_reg_29 <= p_ZZ3firPiiE9shift_reg_28;
        p_ZZ3firPiiE9shift_reg_30 <= p_ZZ3firPiiE9shift_reg_29;
        p_ZZ3firPiiE9shift_reg_31 <= p_ZZ3firPiiE9shift_reg_30;
        p_ZZ3firPiiE9shift_reg_32 <= p_ZZ3firPiiE9shift_reg_31;
        p_ZZ3firPiiE9shift_reg_33 <= p_ZZ3firPiiE9shift_reg_32;
        p_ZZ3firPiiE9shift_reg_34 <= p_ZZ3firPiiE9shift_reg_33;
        p_ZZ3firPiiE9shift_reg_35 <= p_ZZ3firPiiE9shift_reg_34;
        p_ZZ3firPiiE9shift_reg_36 <= p_ZZ3firPiiE9shift_reg_35;
        p_ZZ3firPiiE9shift_reg_37 <= p_ZZ3firPiiE9shift_reg_36;
        p_ZZ3firPiiE9shift_reg_38 <= p_ZZ3firPiiE9shift_reg_37;
        p_ZZ3firPiiE9shift_reg_39 <= p_ZZ3firPiiE9shift_reg_38;
        p_ZZ3firPiiE9shift_reg_40 <= p_ZZ3firPiiE9shift_reg_39;
        p_ZZ3firPiiE9shift_reg_41 <= p_ZZ3firPiiE9shift_reg_40;
        p_ZZ3firPiiE9shift_reg_42 <= p_ZZ3firPiiE9shift_reg_41;
        p_ZZ3firPiiE9shift_reg_43 <= p_ZZ3firPiiE9shift_reg_42;
        p_ZZ3firPiiE9shift_reg_44 <= p_ZZ3firPiiE9shift_reg_43;
        p_ZZ3firPiiE9shift_reg_45 <= p_ZZ3firPiiE9shift_reg_44;
        p_ZZ3firPiiE9shift_reg_46 <= p_ZZ3firPiiE9shift_reg_45;
        p_ZZ3firPiiE9shift_reg_47 <= p_ZZ3firPiiE9shift_reg_46;
        p_ZZ3firPiiE9shift_reg_48 <= p_ZZ3firPiiE9shift_reg_47;
        p_ZZ3firPiiE9shift_reg_49 <= p_ZZ3firPiiE9shift_reg_48;
        p_ZZ3firPiiE9shift_reg_50 <= p_ZZ3firPiiE9shift_reg_49;
        p_ZZ3firPiiE9shift_reg_51 <= p_ZZ3firPiiE9shift_reg_50;
        p_ZZ3firPiiE9shift_reg_52 <= p_ZZ3firPiiE9shift_reg_51;
        p_ZZ3firPiiE9shift_reg_53 <= p_ZZ3firPiiE9shift_reg_52;
        p_ZZ3firPiiE9shift_reg_54 <= p_ZZ3firPiiE9shift_reg_53;
        p_ZZ3firPiiE9shift_reg_55 <= p_ZZ3firPiiE9shift_reg_54;
        p_ZZ3firPiiE9shift_reg_56 <= p_ZZ3firPiiE9shift_reg_55;
        p_ZZ3firPiiE9shift_reg_57 <= p_ZZ3firPiiE9shift_reg_56;
        p_ZZ3firPiiE9shift_reg_58 <= p_ZZ3firPiiE9shift_reg_57;
        p_ZZ3firPiiE9shift_reg_59 <= p_ZZ3firPiiE9shift_reg_58;
        p_ZZ3firPiiE9shift_reg_60 <= p_ZZ3firPiiE9shift_reg_59;
        p_ZZ3firPiiE9shift_reg_61 <= p_ZZ3firPiiE9shift_reg_60;
        p_ZZ3firPiiE9shift_reg_62 <= p_ZZ3firPiiE9shift_reg_61;
        p_ZZ3firPiiE9shift_reg_63 <= p_ZZ3firPiiE9shift_reg_62;
        p_ZZ3firPiiE9shift_reg_64 <= p_ZZ3firPiiE9shift_reg_63;
        p_ZZ3firPiiE9shift_reg_65 <= p_ZZ3firPiiE9shift_reg_64;
        p_ZZ3firPiiE9shift_reg_66 <= p_ZZ3firPiiE9shift_reg_65;
        p_ZZ3firPiiE9shift_reg_67 <= p_ZZ3firPiiE9shift_reg_66;
        p_ZZ3firPiiE9shift_reg_68 <= p_ZZ3firPiiE9shift_reg_67;
        p_ZZ3firPiiE9shift_reg_69 <= p_ZZ3firPiiE9shift_reg_68;
        p_ZZ3firPiiE9shift_reg_70 <= p_ZZ3firPiiE9shift_reg_69;
        p_ZZ3firPiiE9shift_reg_71 <= p_ZZ3firPiiE9shift_reg_70;
        p_ZZ3firPiiE9shift_reg_72 <= p_ZZ3firPiiE9shift_reg_71;
        p_ZZ3firPiiE9shift_reg_73 <= p_ZZ3firPiiE9shift_reg_72;
        p_ZZ3firPiiE9shift_reg_74 <= p_ZZ3firPiiE9shift_reg_73;
        p_ZZ3firPiiE9shift_reg_75 <= p_ZZ3firPiiE9shift_reg_74;
        p_ZZ3firPiiE9shift_reg_76 <= p_ZZ3firPiiE9shift_reg_75;
        p_ZZ3firPiiE9shift_reg_77 <= p_ZZ3firPiiE9shift_reg_76;
        p_ZZ3firPiiE9shift_reg_78 <= p_ZZ3firPiiE9shift_reg_77;
        p_ZZ3firPiiE9shift_reg_79 <= p_ZZ3firPiiE9shift_reg_78;
        p_ZZ3firPiiE9shift_reg_80 <= p_ZZ3firPiiE9shift_reg_79;
        p_ZZ3firPiiE9shift_reg_81 <= p_ZZ3firPiiE9shift_reg_80;
        p_ZZ3firPiiE9shift_reg_82 <= p_ZZ3firPiiE9shift_reg_81;
        p_ZZ3firPiiE9shift_reg_83 <= p_ZZ3firPiiE9shift_reg_82;
        p_ZZ3firPiiE9shift_reg_84 <= p_ZZ3firPiiE9shift_reg_83;
        p_ZZ3firPiiE9shift_reg_85 <= p_ZZ3firPiiE9shift_reg_84;
        p_ZZ3firPiiE9shift_reg_86 <= p_ZZ3firPiiE9shift_reg_85;
        p_ZZ3firPiiE9shift_reg_87 <= p_ZZ3firPiiE9shift_reg_86;
        p_ZZ3firPiiE9shift_reg_88 <= p_ZZ3firPiiE9shift_reg_87;
        p_ZZ3firPiiE9shift_reg_89 <= p_ZZ3firPiiE9shift_reg_88;
        p_ZZ3firPiiE9shift_reg_90 <= p_ZZ3firPiiE9shift_reg_89;
        p_ZZ3firPiiE9shift_reg_91 <= p_ZZ3firPiiE9shift_reg_90;
        p_ZZ3firPiiE9shift_reg_92 <= p_ZZ3firPiiE9shift_reg_91;
        p_ZZ3firPiiE9shift_reg_93 <= p_ZZ3firPiiE9shift_reg_92;
        p_ZZ3firPiiE9shift_reg_94 <= p_ZZ3firPiiE9shift_reg_93;
        p_ZZ3firPiiE9shift_reg_95 <= p_ZZ3firPiiE9shift_reg_94;
        p_ZZ3firPiiE9shift_reg_96 <= p_ZZ3firPiiE9shift_reg_95;
        p_ZZ3firPiiE9shift_reg_97 <= p_ZZ3firPiiE9shift_reg_96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ3firPiiE9shift_reg_100 <= p_ZZ3firPiiE9shift_reg_99;
        p_ZZ3firPiiE9shift_reg_101 <= p_ZZ3firPiiE9shift_reg_100;
        p_ZZ3firPiiE9shift_reg_102 <= p_ZZ3firPiiE9shift_reg_101;
        p_ZZ3firPiiE9shift_reg_103 <= p_ZZ3firPiiE9shift_reg_102;
        p_ZZ3firPiiE9shift_reg_104 <= p_ZZ3firPiiE9shift_reg_103;
        p_ZZ3firPiiE9shift_reg_105 <= p_ZZ3firPiiE9shift_reg_104;
        p_ZZ3firPiiE9shift_reg_106 <= p_ZZ3firPiiE9shift_reg_105;
        p_ZZ3firPiiE9shift_reg_107 <= p_ZZ3firPiiE9shift_reg_106;
        p_ZZ3firPiiE9shift_reg_98 <= p_ZZ3firPiiE9shift_reg_97_load_reg_3166;
        p_ZZ3firPiiE9shift_reg_99 <= p_ZZ3firPiiE9shift_reg_98;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZ3firPiiE9shift_reg_108 <= p_ZZ3firPiiE9shift_reg_107_load_reg_3508;
        p_ZZ3firPiiE9shift_reg_109 <= p_ZZ3firPiiE9shift_reg_108;
        p_ZZ3firPiiE9shift_reg_110 <= p_ZZ3firPiiE9shift_reg_109;
        p_ZZ3firPiiE9shift_reg_111 <= p_ZZ3firPiiE9shift_reg_110;
        p_ZZ3firPiiE9shift_reg_112 <= p_ZZ3firPiiE9shift_reg_111;
        p_ZZ3firPiiE9shift_reg_113 <= p_ZZ3firPiiE9shift_reg_112;
        p_ZZ3firPiiE9shift_reg_114 <= p_ZZ3firPiiE9shift_reg_113;
        p_ZZ3firPiiE9shift_reg_115 <= p_ZZ3firPiiE9shift_reg_114;
        p_ZZ3firPiiE9shift_reg_116 <= p_ZZ3firPiiE9shift_reg_115;
        p_ZZ3firPiiE9shift_reg_117 <= p_ZZ3firPiiE9shift_reg_116;
        p_ZZ3firPiiE9shift_reg_118 <= p_ZZ3firPiiE9shift_reg_117;
        p_ZZ3firPiiE9shift_reg_119 <= p_ZZ3firPiiE9shift_reg_118;
        p_ZZ3firPiiE9shift_reg_120 <= p_ZZ3firPiiE9shift_reg_119;
        p_ZZ3firPiiE9shift_reg_121 <= p_ZZ3firPiiE9shift_reg_120;
        p_ZZ3firPiiE9shift_reg_122 <= p_ZZ3firPiiE9shift_reg_121;
        p_ZZ3firPiiE9shift_reg_123 <= p_ZZ3firPiiE9shift_reg_122;
        p_ZZ3firPiiE9shift_reg_124 <= p_ZZ3firPiiE9shift_reg_123;
        p_ZZ3firPiiE9shift_reg_125 <= p_ZZ3firPiiE9shift_reg_124;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZZ3firPiiE9shift_reg_126 <= p_ZZ3firPiiE9shift_reg_125_load_reg_3636;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to10 = 1'b1;
    end else begin
        ap_idle_pp0_0to10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to10 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_3050_p2 = (add_ln44_78_reg_3859_pp0_iter7_reg + add_ln44_62_reg_3879);

assign add_ln44_100_fu_2919_p2 = (add_ln44_99_reg_3798 + add_ln44_94_reg_3793);

assign add_ln44_101_fu_2551_p2 = (p_ZZ3firPiiE9shift_reg_113 + p_ZZ3firPiiE9shift_reg_114);

assign add_ln44_102_fu_2557_p2 = (add_ln44_101_fu_2551_p2 + p_ZZ3firPiiE9shift_reg_115);

assign add_ln44_103_fu_2563_p2 = (p_ZZ3firPiiE9shift_reg_110 + p_ZZ3firPiiE9shift_reg_111);

assign add_ln44_104_fu_2569_p2 = (add_ln44_103_fu_2563_p2 + p_ZZ3firPiiE9shift_reg_112);

assign add_ln44_105_fu_2801_p2 = (add_ln44_104_reg_3712 + add_ln44_102_reg_3707);

assign add_ln44_106_fu_2575_p2 = (p_ZZ3firPiiE9shift_reg_107_load_reg_3508 + p_ZZ3firPiiE9shift_reg_108);

assign add_ln44_107_fu_2580_p2 = (add_ln44_106_fu_2575_p2 + p_ZZ3firPiiE9shift_reg_109);

assign add_ln44_108_fu_2017_p2 = (p_ZZ3firPiiE9shift_reg_106 + p_ZZ3firPiiE9shift_reg_104);

assign add_ln44_109_fu_2023_p2 = (p_ZZ3firPiiE9shift_reg_105 + p_ZZ3firPiiE9shift_reg_79_load_reg_3210);

assign add_ln44_10_fu_2950_p2 = (add_ln44_9_reg_3828 + add_ln44_4_fu_2946_p2);

assign add_ln44_110_fu_2028_p2 = (add_ln44_109_fu_2023_p2 + add_ln44_108_fu_2017_p2);

assign add_ln44_111_fu_2586_p2 = (add_ln44_110_reg_3560 + add_ln44_107_fu_2580_p2);

assign add_ln44_112_fu_2805_p2 = (add_ln44_111_reg_3717 + add_ln44_105_fu_2801_p2);

assign add_ln44_113_fu_2923_p2 = (add_ln44_112_reg_3803 + add_ln44_100_fu_2919_p2);

assign add_ln44_114_fu_2969_p2 = (shl_ln44_22_fu_2959_p2 + shl_ln44_23_fu_2964_p2);

assign add_ln44_115_fu_2975_p2 = (add_ln44_114_fu_2969_p2 + add_ln44_90_fu_2955_p2);

assign add_ln44_116_fu_1461_p2 = (shl_ln44_33_fu_1449_p2 + shl_ln44_34_fu_1455_p2);

assign add_ln44_117_fu_2991_p2 = (shl_ln44_35_fu_2981_p2 + shl_ln44_36_fu_2986_p2);

assign add_ln44_118_fu_3012_p2 = (shl_ln44_38_fu_3002_p2 + shl_ln44_39_fu_3007_p2);

assign add_ln44_119_fu_3034_p2 = (shl_ln44_40_fu_3024_p2 + shl_ln44_41_fu_3029_p2);

assign add_ln44_11_fu_2002_p2 = (sub_ln44_3_reg_3333 + shl_ln44_16_fu_1992_p2);

assign add_ln44_121_fu_2642_p2 = (shl_ln44_53_fu_2632_p2 + shl_ln44_54_fu_2637_p2);

assign add_ln44_122_fu_2087_p2 = (shl_ln44_62_fu_2077_p2 + shl_ln44_63_fu_2082_p2);

assign add_ln44_123_fu_2103_p2 = (shl_ln44_64_fu_2093_p2 + shl_ln44_65_fu_2098_p2);

assign add_ln44_124_fu_3086_p2 = (shl_ln44_66_fu_3076_p2 + shl_ln44_67_fu_3081_p2);

assign add_ln44_125_fu_3064_p2 = (shl_ln44_72_fu_3054_p2 + shl_ln44_73_fu_3059_p2);

assign add_ln44_126_fu_1737_p2 = (p_ZZ3firPiiE9shift_reg_21 + p_ZZ3firPiiE9shift_reg_22);

assign add_ln44_127_fu_1743_p2 = (add_ln44_126_fu_1737_p2 + p_ZZ3firPiiE9shift_reg_23);

assign add_ln44_128_fu_1749_p2 = (p_ZZ3firPiiE9shift_reg_18 + p_ZZ3firPiiE9shift_reg_19);

assign add_ln44_129_fu_1755_p2 = (add_ln44_128_fu_1749_p2 + p_ZZ3firPiiE9shift_reg_20);

assign add_ln44_12_fu_2007_p2 = (add_ln44_11_fu_2002_p2 + sub_ln44_9_reg_3338);

assign add_ln44_130_fu_2664_p2 = (add_ln44_129_reg_3470_pp0_iter1_reg + add_ln44_127_reg_3465_pp0_iter1_reg);

assign add_ln44_131_fu_1761_p2 = (p_ZZ3firPiiE9shift_reg_15 + p_ZZ3firPiiE9shift_reg_16);

assign add_ln44_132_fu_2156_p2 = (add_ln44_131_reg_3475 + p_ZZ3firPiiE9shift_reg_17_load_reg_3307);

assign add_ln44_133_fu_2160_p2 = (add_ln44_19_reg_3480 + add_ln44_132_fu_2156_p2);

assign add_ln44_134_fu_2668_p2 = (add_ln44_133_reg_3611 + add_ln44_130_fu_2664_p2);

assign add_ln44_135_fu_3107_p2 = (shl_ln44_78_fu_3097_p2 + shl_ln44_79_fu_3102_p2);

assign add_ln44_13_fu_2451_p2 = (sub_ln44_7_fu_2419_p2 + mul_ln44_4_reg_3545);

assign add_ln44_14_fu_2901_p2 = (sub_ln44_14_reg_3662_pp0_iter3_reg + add_ln44_12_reg_3555_pp0_iter3_reg);

assign add_ln44_15_fu_1353_p2 = (p_ZZ3firPiiE9shift_reg_89 + p_ZZ3firPiiE9shift_reg_90);

assign add_ln44_16_fu_1359_p2 = (add_ln44_15_fu_1353_p2 + p_ZZ3firPiiE9shift_reg_91);

assign add_ln44_17_fu_1365_p2 = (p_ZZ3firPiiE9shift_reg_86 + p_ZZ3firPiiE9shift_reg_87);

assign add_ln44_18_fu_1767_p2 = (p_ZZ3firPiiE9shift_reg_12 + p_ZZ3firPiiE9shift_reg_13);

assign add_ln44_19_fu_1773_p2 = (add_ln44_18_fu_1767_p2 + p_ZZ3firPiiE9shift_reg_14);

assign add_ln44_1_fu_2124_p2 = (add_ln44_fu_2119_p2 + sub_ln44_41_reg_3439);

assign add_ln44_20_fu_2753_p2 = (mul_ln44_13_reg_3672 + sub_ln44_1_reg_3647);

assign add_ln44_22_fu_3150_p2 = (sub_ln44_50_reg_3894 + add_ln44_10_reg_3864_pp0_iter10_reg);

assign add_ln44_23_fu_3070_p2 = (add_ln44_125_fu_3064_p2 + acc_fu_3050_p2);

assign add_ln44_24_fu_3092_p2 = (add_ln44_23_reg_3884 + add_ln44_124_fu_3086_p2);

assign add_ln44_25_fu_1779_p2 = (p_ZZ3firPiiE9shift_reg_42 + p_ZZ3firPiiE9shift_reg_43);

assign add_ln44_26_fu_1785_p2 = (add_ln44_25_fu_1779_p2 + p_ZZ3firPiiE9shift_reg_44);

assign add_ln44_27_fu_3113_p2 = (add_ln44_135_fu_3107_p2 + add_ln44_24_fu_3092_p2);

assign add_ln44_28_fu_2165_p2 = (sub_ln44_39_reg_3434 + add_ln44_123_fu_2103_p2);

assign add_ln44_29_fu_2673_p2 = (add_ln44_28_reg_3616 + add_ln44_121_fu_2642_p2);

assign add_ln44_2_fu_2653_p2 = (sub_ln44_37_fu_2627_p2 + mul_ln44_reg_3596);

assign add_ln44_30_fu_2170_p2 = (sub_ln44_36_fu_2072_p2 + shl_ln44_68_fu_2109_p2);

assign add_ln44_31_fu_2176_p2 = (add_ln44_30_fu_2170_p2 + sub_ln44_43_reg_3444);

assign add_ln44_32_fu_2678_p2 = (add_ln44_31_reg_3621 + add_ln44_29_fu_2673_p2);

assign add_ln44_33_fu_3141_p2 = (add_ln44_32_reg_3758_pp0_iter9_reg + add_ln44_27_reg_3889);

assign add_ln44_35_fu_2688_p2 = (sub_ln44_51_fu_2683_p2 + mul_ln44_21_reg_3591);

assign add_ln44_36_fu_2757_p2 = (add_ln44_20_fu_2753_p2 + sub_ln44_16_reg_3667);

assign add_ln44_37_fu_2715_p2 = (sub_ln44_53_fu_2709_p2 + mul_ln44_5_reg_3581);

assign add_ln44_38_fu_2892_p2 = (add_ln44_37_reg_3768 + add_ln44_35_reg_3763);

assign add_ln44_39_fu_1791_p2 = (p_ZZ3firPiiE9shift_reg_30 + p_ZZ3firPiiE9shift_reg_31);

assign add_ln44_40_fu_2905_p2 = (add_ln44_36_reg_3778 + add_ln44_14_fu_2901_p2);

assign add_ln44_41_fu_2484_p2 = (shl_ln44_11_fu_2424_p2 + sub_ln44_11_reg_3540);

assign add_ln44_42_fu_2203_p2 = (sub_ln44_45_reg_3449 + add_ln44_122_fu_2087_p2);

assign add_ln44_43_fu_2720_p2 = (add_ln44_42_reg_3631 + sub_ln44_57_reg_3503_pp0_iter1_reg);

assign add_ln44_44_fu_2724_p2 = (add_ln44_43_fu_2720_p2 + sub_ln44_55_reg_3626);

assign add_ln44_45_fu_2896_p2 = (add_ln44_44_reg_3773 + add_ln44_38_fu_2892_p2);

assign add_ln44_46_fu_3145_p2 = (add_ln44_45_reg_3833_pp0_iter9_reg + add_ln44_33_fu_3141_p2);

assign add_ln44_47_fu_1797_p2 = (p_ZZ3firPiiE9shift_reg_27 + p_ZZ3firPiiE9shift_reg_28);

assign add_ln44_48_fu_2997_p2 = (add_ln44_117_fu_2991_p2 + add_ln44_115_reg_3869);

assign add_ln44_49_fu_1473_p2 = (p_ZZ3firPiiE9shift_reg_77 + p_ZZ3firPiiE9shift_reg_76);

assign add_ln44_4_fu_2946_p2 = (sub_ln44_46_reg_3742_pp0_iter3_reg + add_ln44_1_reg_3601_pp0_iter3_reg);

assign add_ln44_50_fu_3018_p2 = (add_ln44_118_fu_3012_p2 + add_ln44_48_fu_2997_p2);

assign add_ln44_51_fu_1479_p2 = (p_ZZ3firPiiE9shift_reg_75 + p_ZZ3firPiiE9shift_reg_74);

assign add_ln44_52_fu_1485_p2 = (p_ZZ3firPiiE9shift_reg_73 + p_ZZ3firPiiE9shift_reg_72);

assign add_ln44_53_fu_1491_p2 = (add_ln44_52_fu_1485_p2 + add_ln44_51_fu_1479_p2);

assign add_ln44_54_fu_3040_p2 = (add_ln44_119_fu_3034_p2 + add_ln44_50_reg_3874);

assign add_ln44_55_fu_1497_p2 = (p_ZZ3firPiiE9shift_reg_71 + p_ZZ3firPiiE9shift_reg_70);

assign add_ln44_56_fu_1503_p2 = (shl_ln44_37_fu_1467_p2 + sub_ln44_24_fu_1437_p2);

assign add_ln44_57_fu_2928_p2 = (add_ln44_56_reg_3394_pp0_iter3_reg + sub_ln44_27_reg_3808);

assign add_ln44_59_fu_1509_p2 = (p_ZZ3firPiiE9shift_reg_65 + p_ZZ3firPiiE9shift_reg_64);

assign add_ln44_5_fu_1719_p2 = (fir_int_int_shift_reg_9 + p_ZZ3firPiiE9shift_reg_10);

assign add_ln44_60_fu_2846_p2 = (mul_ln44_20_reg_3727 + sub_ln44_28_fu_2841_p2);

assign add_ln44_61_fu_2932_p2 = (add_ln44_60_reg_3813 + add_ln44_57_fu_2928_p2);

assign add_ln44_62_fu_3045_p2 = (add_ln44_61_reg_3854_pp0_iter6_reg + add_ln44_54_fu_3040_p2);

assign add_ln44_63_fu_1515_p2 = (p_ZZ3firPiiE9shift_reg_63 + p_ZZ3firPiiE9shift_reg_62);

assign add_ln44_64_fu_1521_p2 = (p_ZZ3firPiiE9shift_reg_61 + p_ZZ3firPiiE9shift_reg_60);

assign add_ln44_65_fu_2044_p2 = (add_ln44_64_reg_3409 + add_ln44_63_reg_3404);

assign add_ln44_66_fu_1527_p2 = (p_ZZ3firPiiE9shift_reg_59 + p_ZZ3firPiiE9shift_reg_58);

assign add_ln44_67_fu_1533_p2 = (p_ZZ3firPiiE9shift_reg_57 + p_ZZ3firPiiE9shift_reg_56);

assign add_ln44_68_fu_1539_p2 = (add_ln44_67_fu_1533_p2 + add_ln44_66_fu_1527_p2);

assign add_ln44_69_fu_2048_p2 = (add_ln44_68_reg_3414 + add_ln44_65_fu_2044_p2);

assign add_ln44_6_fu_1725_p2 = (add_ln44_5_fu_1719_p2 + p_ZZ3firPiiE9shift_reg_11);

assign add_ln44_70_fu_1545_p2 = (p_ZZ3firPiiE9shift_reg_55 + p_ZZ3firPiiE9shift_reg_54);

assign add_ln44_72_fu_2878_p2 = (sub_ln44_31_fu_2873_p2 + mul_ln44_23_reg_3732);

assign add_ln44_73_fu_2606_p2 = (sub_ln44_25_fu_2601_p2 + shl_ln44_28_fu_2591_p2);

assign add_ln44_74_fu_2058_p2 = (sub_ln44_21_reg_3360 + add_ln44_116_reg_3370);

assign add_ln44_75_fu_2062_p2 = (add_ln44_74_fu_2058_p2 + sub_ln44_23_reg_3365);

assign add_ln44_76_fu_2612_p2 = (add_ln44_75_reg_3576 + add_ln44_73_fu_2606_p2);

assign add_ln44_77_fu_2937_p2 = (add_ln44_76_reg_3737_pp0_iter3_reg + add_ln44_72_reg_3823);

assign add_ln44_78_fu_2941_p2 = (add_ln44_77_fu_2937_p2 + sub_ln44_30_reg_3818);

assign add_ln44_79_fu_1803_p2 = (add_ln44_47_fu_1797_p2 + p_ZZ3firPiiE9shift_reg_29);

assign add_ln44_7_fu_1731_p2 = (fir_int_int_shift_reg_6 + fir_int_int_shift_reg_7);

assign add_ln44_80_fu_1809_p2 = (p_ZZ3firPiiE9shift_reg_26 + p_ZZ3firPiiE9shift_reg_24);

assign add_ln44_81_fu_2489_p2 = (add_ln44_41_fu_2484_p2 + sub_ln44_5_reg_3535);

assign add_ln44_82_fu_2767_p2 = (sub_ln44_17_fu_2762_p2 + sub_ln44_6_fu_2743_p2);

assign add_ln44_83_fu_2910_p2 = (add_ln44_82_reg_3783 + add_ln44_81_reg_3677_pp0_iter3_reg);

assign add_ln44_84_fu_2494_p2 = (sub_ln44_13_fu_2445_p2 + mul_ln44_6_reg_3550);

assign add_ln44_85_fu_2773_p2 = (add_ln44_84_reg_3682 + mul_ln44_7_reg_3657);

assign add_ln44_86_fu_1371_p2 = (p_ZZ3firPiiE9shift_reg_92 + p_ZZ3firPiiE9shift_reg_93);

assign add_ln44_87_fu_1377_p2 = (add_ln44_86_fu_1371_p2 + p_ZZ3firPiiE9shift_reg_94);

assign add_ln44_88_fu_2777_p2 = (sub_ln44_19_reg_3687 + add_ln44_85_fu_2773_p2);

assign add_ln44_89_fu_2914_p2 = (add_ln44_88_reg_3788 + add_ln44_83_fu_2910_p2);

assign add_ln44_8_fu_2883_p2 = (mul_ln44_24_reg_3747 + sub_ln44_33_reg_3424_pp0_iter2_reg);

assign add_ln44_90_fu_2955_p2 = (add_ln44_89_reg_3843 + add_ln44_40_reg_3838);

assign add_ln44_91_fu_2782_p2 = (p_ZZ3firPiiE9shift_reg_125_load_reg_3636 + p_ZZ3firPiiE9shift_reg_126);

assign add_ln44_92_fu_2521_p2 = (p_ZZ3firPiiE9shift_reg_122 + p_ZZ3firPiiE9shift_reg_123);

assign add_ln44_93_fu_2527_p2 = (add_ln44_92_fu_2521_p2 + p_ZZ3firPiiE9shift_reg_124);

assign add_ln44_94_fu_2787_p2 = (add_ln44_93_reg_3692 + add_ln44_91_fu_2782_p2);

assign add_ln44_95_fu_2533_p2 = (p_ZZ3firPiiE9shift_reg_119 + p_ZZ3firPiiE9shift_reg_120);

assign add_ln44_96_fu_2792_p2 = (add_ln44_95_reg_3697 + p_ZZ3firPiiE9shift_reg_121_load_reg_3642);

assign add_ln44_97_fu_2539_p2 = (p_ZZ3firPiiE9shift_reg_116 + p_ZZ3firPiiE9shift_reg_117);

assign add_ln44_98_fu_2545_p2 = (add_ln44_97_fu_2539_p2 + p_ZZ3firPiiE9shift_reg_118);

assign add_ln44_99_fu_2796_p2 = (add_ln44_98_reg_3702 + add_ln44_96_fu_2792_p2);

assign add_ln44_9_fu_2887_p2 = (add_ln44_8_fu_2883_p2 + sub_ln44_48_reg_3606_pp0_iter2_reg);

assign add_ln44_fu_2119_p2 = (sub_ln44_35_reg_3429 + shl_ln44_71_fu_2114_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_1341_p1 = 32'd4294967293;

assign grp_fu_1347_p1 = 32'd4294967285;

assign grp_fu_1443_p1 = 32'd4294967293;

assign grp_fu_1599_p1 = 32'd4294967285;

assign grp_fu_1605_p1 = 32'd4294967285;

assign grp_fu_1683_p1 = 32'd4294967293;

assign grp_fu_1713_p1 = 32'd4294967293;

assign grp_fu_1962_p1 = 32'd4294967293;

assign grp_fu_1997_p1 = 32'd4294967285;

assign grp_fu_2012_p1 = 32'd4294967285;

assign grp_fu_2034_p1 = 32'd4294967293;

assign grp_fu_2039_p1 = 32'd4294967285;

assign grp_fu_2053_p1 = 32'd4294967285;

assign grp_fu_2151_p1 = 32'd4294967285;

assign shl_ln44_10_fu_1323_p2 = p_ZZ3firPiiE9shift_reg_81 << 32'd2;

assign shl_ln44_11_fu_2424_p2 = p_ZZ3firPiiE9shift_reg_101_load_reg_3514 << 32'd3;

assign shl_ln44_12_fu_1968_p2 = p_ZZ3firPiiE9shift_reg_102 << 32'd4;

assign shl_ln44_13_fu_1974_p2 = p_ZZ3firPiiE9shift_reg_102 << 32'd2;

assign shl_ln44_14_fu_2429_p2 = fir_int_int_shift_reg_reg_3177_pp0_iter1_reg << 32'd3;

assign shl_ln44_15_fu_2440_p2 = fir_int_int_shift_reg_reg_3177_pp0_iter1_reg << 32'd1;

assign shl_ln44_16_fu_1992_p2 = fir_int_int_shift_reg_12_reg_3205 << 32'd3;

assign shl_ln44_17_fu_2748_p2 = p_ZZ3firPiiE9shift_reg_98_load_reg_3530_pp0_iter2_reg << 32'd3;

assign shl_ln44_18_fu_2462_p2 = add_ln44_16_reg_3343_pp0_iter1_reg << 32'd3;

assign shl_ln44_19_fu_2473_p2 = add_ln44_16_reg_3343_pp0_iter1_reg << 32'd1;

assign shl_ln44_1_fu_2398_p2 = p_ZZ3firPiiE9shift_reg_88_load_reg_3183_pp0_iter1_reg << 32'd1;

assign shl_ln44_20_fu_2499_p2 = add_ln44_87_reg_3354_pp0_iter1_reg << 32'd3;

assign shl_ln44_21_fu_2510_p2 = add_ln44_87_reg_3354_pp0_iter1_reg << 32'd1;

assign shl_ln44_22_fu_2959_p2 = add_ln44_113_reg_3848 << 32'd3;

assign shl_ln44_23_fu_2964_p2 = add_ln44_113_reg_3848 << 32'd1;

assign shl_ln44_24_fu_1383_p2 = p_ZZ3firPiiE9shift_reg_48 << 32'd4;

assign shl_ln44_25_fu_1389_p2 = p_ZZ3firPiiE9shift_reg_48 << 32'd2;

assign shl_ln44_26_fu_1407_p2 = p_ZZ3firPiiE9shift_reg_49 << 32'd4;

assign shl_ln44_27_fu_1413_p2 = p_ZZ3firPiiE9shift_reg_49 << 32'd2;

assign shl_ln44_28_fu_2591_p2 = p_ZZ3firPiiE9shift_reg_50_load_reg_3247_pp0_iter1_reg << 32'd3;

assign shl_ln44_29_fu_1431_p2 = p_ZZ3firPiiE9shift_reg_68 << 32'd2;

assign shl_ln44_2_fu_1293_p2 = p_ZZ3firPiiE9shift_reg_80 << 32'd4;

assign shl_ln44_30_fu_2596_p2 = fir_int_int_shift_reg_28_reg_3241_pp0_iter1_reg << 32'd2;

assign shl_ln44_31_fu_2810_p2 = fir_int_int_shift_reg_26_reg_3231_pp0_iter2_reg << 32'd3;

assign shl_ln44_32_fu_2815_p2 = p_ZZ3firPiiE9shift_reg_66_load_reg_3226_pp0_iter2_reg << 32'd3;

assign shl_ln44_33_fu_1449_p2 = p_ZZ3firPiiE9shift_reg_47 << 32'd3;

assign shl_ln44_34_fu_1455_p2 = p_ZZ3firPiiE9shift_reg_47 << 32'd1;

assign shl_ln44_35_fu_2981_p2 = p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter5_reg << 32'd3;

assign shl_ln44_36_fu_2986_p2 = p_ZZ3firPiiE9shift_reg_78_load_reg_3215_pp0_iter5_reg << 32'd1;

assign shl_ln44_37_fu_1467_p2 = p_ZZ3firPiiE9shift_reg_69 << 32'd3;

assign shl_ln44_38_fu_3002_p2 = add_ln44_49_reg_3375_pp0_iter5_reg << 32'd3;

assign shl_ln44_39_fu_3007_p2 = add_ln44_49_reg_3375_pp0_iter5_reg << 32'd1;

assign shl_ln44_3_fu_1299_p2 = p_ZZ3firPiiE9shift_reg_80 << 32'd2;

assign shl_ln44_40_fu_3024_p2 = add_ln44_53_reg_3381_pp0_iter6_reg << 32'd3;

assign shl_ln44_41_fu_3029_p2 = add_ln44_53_reg_3381_pp0_iter6_reg << 32'd1;

assign shl_ln44_42_fu_2820_p2 = add_ln44_55_reg_3387_pp0_iter2_reg << 32'd4;

assign shl_ln44_43_fu_2825_p2 = add_ln44_55_reg_3387_pp0_iter2_reg << 32'd2;

assign shl_ln44_44_fu_2851_p2 = add_ln44_69_reg_3570_pp0_iter2_reg << 32'd3;

assign shl_ln44_45_fu_2862_p2 = add_ln44_69_reg_3570_pp0_iter2_reg << 32'd1;

assign shl_ln44_46_fu_1551_p2 = fir_int_int_shift_reg_8 << 32'd3;

assign shl_ln44_47_fu_1563_p2 = fir_int_int_shift_reg_8 << 32'd1;

assign shl_ln44_48_fu_1575_p2 = fir_int_int_shift_reg << 32'd4;

assign shl_ln44_49_fu_1581_p2 = fir_int_int_shift_reg << 32'd2;

assign shl_ln44_4_fu_1938_p2 = p_ZZ3firPiiE9shift_reg_103 << 32'd4;

assign shl_ln44_50_fu_2067_p2 = p_ZZ3firPiiE9shift_reg_36_load_reg_3281 << 32'd2;

assign shl_ln44_51_fu_2617_p2 = fir_int_int_shift_reg_5_load_reg_3312_pp0_iter1_reg << 32'd3;

assign shl_ln44_52_fu_2622_p2 = fir_int_int_shift_reg_3_load_reg_3322_pp0_iter1_reg << 32'd2;

assign shl_ln44_53_fu_2632_p2 = fir_int_int_shift_reg_33_reg_3264_pp0_iter1_reg << 32'd3;

assign shl_ln44_54_fu_2637_p2 = fir_int_int_shift_reg_33_reg_3264_pp0_iter1_reg << 32'd1;

assign shl_ln44_55_fu_1611_p2 = p_ZZ3firPiiE9shift_reg_39 << 32'd4;

assign shl_ln44_56_fu_1617_p2 = p_ZZ3firPiiE9shift_reg_39 << 32'd2;

assign shl_ln44_57_fu_1635_p2 = fir_int_int_shift_reg_1 << 32'd4;

assign shl_ln44_58_fu_1641_p2 = fir_int_int_shift_reg_1 << 32'd2;

assign shl_ln44_59_fu_1659_p2 = p_ZZ3firPiiE9shift_reg_38 << 32'd4;

assign shl_ln44_5_fu_1944_p2 = p_ZZ3firPiiE9shift_reg_103 << 32'd2;

assign shl_ln44_60_fu_1665_p2 = p_ZZ3firPiiE9shift_reg_38 << 32'd2;

assign shl_ln44_61_fu_2648_p2 = fir_int_int_shift_reg_35_reg_3292_pp0_iter1_reg << 32'd3;

assign shl_ln44_62_fu_2077_p2 = x_read_reg_3160 << 32'd3;

assign shl_ln44_63_fu_2082_p2 = x_read_reg_3160 << 32'd1;

assign shl_ln44_64_fu_2093_p2 = p_ZZ3firPiiE9shift_reg_40_load_reg_3270 << 32'd3;

assign shl_ln44_65_fu_2098_p2 = p_ZZ3firPiiE9shift_reg_40_load_reg_3270 << 32'd1;

assign shl_ln44_66_fu_3076_p2 = p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter8_reg << 32'd3;

assign shl_ln44_67_fu_3081_p2 = p_ZZ3firPiiE9shift_reg_46_load_reg_3252_pp0_iter8_reg << 32'd1;

assign shl_ln44_68_fu_2109_p2 = p_ZZ3firPiiE9shift_reg_37_load_reg_3276 << 32'd3;

assign shl_ln44_69_fu_1689_p2 = p_ZZ3firPiiE9shift_reg_25 << 32'd3;

assign shl_ln44_6_fu_2738_p2 = p_ZZ3firPiiE9shift_reg_100_load_reg_3519_pp0_iter2_reg << 32'd2;

assign shl_ln44_70_fu_1701_p2 = p_ZZ3firPiiE9shift_reg_25 << 32'd1;

assign shl_ln44_71_fu_2114_p2 = fir_int_int_shift_reg_2_load_reg_3328 << 32'd3;

assign shl_ln44_72_fu_3054_p2 = fir_int_int_shift_reg_29_reg_3258_pp0_iter7_reg << 32'd3;

assign shl_ln44_73_fu_3059_p2 = fir_int_int_shift_reg_29_reg_3258_pp0_iter7_reg << 32'd1;

assign shl_ln44_74_fu_2129_p2 = add_ln44_6_reg_3454 << 32'd3;

assign shl_ln44_75_fu_2140_p2 = add_ln44_6_reg_3454 << 32'd1;

assign shl_ln44_76_fu_3119_p2 = add_ln44_134_reg_3752_pp0_iter9_reg << 32'd3;

assign shl_ln44_77_fu_3130_p2 = add_ln44_134_reg_3752_pp0_iter9_reg << 32'd1;

assign shl_ln44_78_fu_3097_p2 = add_ln44_26_reg_3485_pp0_iter8_reg << 32'd3;

assign shl_ln44_79_fu_3102_p2 = add_ln44_26_reg_3485_pp0_iter8_reg << 32'd1;

assign shl_ln44_7_fu_2409_p2 = fir_int_int_shift_reg_9_reg_3189_pp0_iter1_reg << 32'd3;

assign shl_ln44_80_fu_2693_p2 = add_ln44_39_reg_3491_pp0_iter1_reg << 32'd3;

assign shl_ln44_81_fu_2704_p2 = add_ln44_39_reg_3491_pp0_iter1_reg << 32'd1;

assign shl_ln44_82_fu_2181_p2 = add_ln44_79_reg_3497 << 32'd3;

assign shl_ln44_83_fu_2192_p2 = add_ln44_79_reg_3497 << 32'd1;

assign shl_ln44_84_fu_1815_p2 = add_ln44_80_fu_1809_p2 << 32'd3;

assign shl_ln44_85_fu_1827_p2 = add_ln44_80_fu_1809_p2 << 32'd1;

assign shl_ln44_8_fu_2414_p2 = fir_int_int_shift_reg_11_reg_3199_pp0_iter1_reg << 32'd2;

assign shl_ln44_9_fu_1317_p2 = p_ZZ3firPiiE9shift_reg_81 << 32'd4;

assign shl_ln44_fu_2387_p2 = p_ZZ3firPiiE9shift_reg_88_load_reg_3183_pp0_iter1_reg << 32'd3;

assign sub_ln44_10_fu_1980_p2 = (shl_ln44_12_fu_1968_p2 - shl_ln44_13_fu_1974_p2);

assign sub_ln44_11_fu_1986_p2 = (sub_ln44_10_fu_1980_p2 - p_ZZ3firPiiE9shift_reg_102);

assign sub_ln44_12_fu_2434_p2 = (32'd0 - shl_ln44_14_fu_2429_p2);

assign sub_ln44_13_fu_2445_p2 = (sub_ln44_12_fu_2434_p2 - shl_ln44_15_fu_2440_p2);

assign sub_ln44_14_fu_2456_p2 = (add_ln44_13_fu_2451_p2 - shl_ln44_7_fu_2409_p2);

assign sub_ln44_15_fu_2467_p2 = (32'd0 - shl_ln44_18_fu_2462_p2);

assign sub_ln44_16_fu_2478_p2 = (sub_ln44_15_fu_2467_p2 - shl_ln44_19_fu_2473_p2);

assign sub_ln44_17_fu_2762_p2 = (mul_ln44_2_reg_3652 - shl_ln44_17_fu_2748_p2);

assign sub_ln44_18_fu_2504_p2 = (32'd0 - shl_ln44_20_fu_2499_p2);

assign sub_ln44_19_fu_2515_p2 = (sub_ln44_18_fu_2504_p2 - shl_ln44_21_fu_2510_p2);

assign sub_ln44_1_fu_2403_p2 = (sub_ln44_fu_2392_p2 - shl_ln44_1_fu_2398_p2);

assign sub_ln44_20_fu_1395_p2 = (shl_ln44_24_fu_1383_p2 - shl_ln44_25_fu_1389_p2);

assign sub_ln44_21_fu_1401_p2 = (sub_ln44_20_fu_1395_p2 - p_ZZ3firPiiE9shift_reg_48);

assign sub_ln44_22_fu_1419_p2 = (shl_ln44_26_fu_1407_p2 - shl_ln44_27_fu_1413_p2);

assign sub_ln44_23_fu_1425_p2 = (sub_ln44_22_fu_1419_p2 - p_ZZ3firPiiE9shift_reg_49);

assign sub_ln44_24_fu_1437_p2 = (shl_ln44_29_fu_1431_p2 - p_ZZ3firPiiE9shift_reg_68);

assign sub_ln44_25_fu_2601_p2 = (shl_ln44_30_fu_2596_p2 - fir_int_int_shift_reg_28_reg_3241_pp0_iter1_reg);

assign sub_ln44_26_fu_2830_p2 = (shl_ln44_42_fu_2820_p2 - shl_ln44_43_fu_2825_p2);

assign sub_ln44_27_fu_2836_p2 = (sub_ln44_26_fu_2830_p2 - add_ln44_55_reg_3387_pp0_iter2_reg);

assign sub_ln44_28_fu_2841_p2 = (mul_ln44_15_reg_3722 - shl_ln44_32_fu_2815_p2);

assign sub_ln44_29_fu_2856_p2 = (32'd0 - shl_ln44_44_fu_2851_p2);

assign sub_ln44_2_fu_1305_p2 = (shl_ln44_2_fu_1293_p2 - shl_ln44_3_fu_1299_p2);

assign sub_ln44_30_fu_2867_p2 = (sub_ln44_29_fu_2856_p2 - shl_ln44_45_fu_2862_p2);

assign sub_ln44_31_fu_2873_p2 = (mul_ln44_19_reg_3565_pp0_iter2_reg - shl_ln44_31_fu_2810_p2);

assign sub_ln44_32_fu_1557_p2 = (32'd0 - shl_ln44_46_fu_1551_p2);

assign sub_ln44_33_fu_1569_p2 = (sub_ln44_32_fu_1557_p2 - shl_ln44_47_fu_1563_p2);

assign sub_ln44_34_fu_1587_p2 = (shl_ln44_48_fu_1575_p2 - shl_ln44_49_fu_1581_p2);

assign sub_ln44_35_fu_1593_p2 = (sub_ln44_34_fu_1587_p2 - fir_int_int_shift_reg);

assign sub_ln44_36_fu_2072_p2 = (shl_ln44_50_fu_2067_p2 - p_ZZ3firPiiE9shift_reg_36_load_reg_3281);

assign sub_ln44_37_fu_2627_p2 = (shl_ln44_52_fu_2622_p2 - fir_int_int_shift_reg_3_load_reg_3322_pp0_iter1_reg);

assign sub_ln44_38_fu_1623_p2 = (shl_ln44_55_fu_1611_p2 - shl_ln44_56_fu_1617_p2);

assign sub_ln44_39_fu_1629_p2 = (sub_ln44_38_fu_1623_p2 - p_ZZ3firPiiE9shift_reg_39);

assign sub_ln44_3_fu_1311_p2 = (sub_ln44_2_fu_1305_p2 - p_ZZ3firPiiE9shift_reg_80);

assign sub_ln44_40_fu_1647_p2 = (shl_ln44_57_fu_1635_p2 - shl_ln44_58_fu_1641_p2);

assign sub_ln44_41_fu_1653_p2 = (sub_ln44_40_fu_1647_p2 - fir_int_int_shift_reg_1);

assign sub_ln44_42_fu_1671_p2 = (shl_ln44_59_fu_1659_p2 - shl_ln44_60_fu_1665_p2);

assign sub_ln44_43_fu_1677_p2 = (sub_ln44_42_fu_1671_p2 - p_ZZ3firPiiE9shift_reg_38);

assign sub_ln44_44_fu_1695_p2 = (32'd0 - shl_ln44_69_fu_1689_p2);

assign sub_ln44_45_fu_1707_p2 = (sub_ln44_44_fu_1695_p2 - shl_ln44_70_fu_1701_p2);

assign sub_ln44_46_fu_2658_p2 = (add_ln44_2_fu_2653_p2 - shl_ln44_51_fu_2617_p2);

assign sub_ln44_47_fu_2134_p2 = (32'd0 - shl_ln44_74_fu_2129_p2);

assign sub_ln44_48_fu_2145_p2 = (sub_ln44_47_fu_2134_p2 - shl_ln44_75_fu_2140_p2);

assign sub_ln44_49_fu_3124_p2 = (32'd0 - shl_ln44_76_fu_3119_p2);

assign sub_ln44_4_fu_1950_p2 = (shl_ln44_4_fu_1938_p2 - shl_ln44_5_fu_1944_p2);

assign sub_ln44_50_fu_3135_p2 = (sub_ln44_49_fu_3124_p2 - shl_ln44_77_fu_3130_p2);

assign sub_ln44_51_fu_2683_p2 = (mul_ln44_9_reg_3586 - shl_ln44_61_fu_2648_p2);

assign sub_ln44_52_fu_2698_p2 = (32'd0 - shl_ln44_80_fu_2693_p2);

assign sub_ln44_53_fu_2709_p2 = (sub_ln44_52_fu_2698_p2 - shl_ln44_81_fu_2704_p2);

assign sub_ln44_54_fu_2186_p2 = (32'd0 - shl_ln44_82_fu_2181_p2);

assign sub_ln44_55_fu_2197_p2 = (sub_ln44_54_fu_2186_p2 - shl_ln44_83_fu_2192_p2);

assign sub_ln44_56_fu_1821_p2 = (32'd0 - shl_ln44_84_fu_1815_p2);

assign sub_ln44_57_fu_1833_p2 = (sub_ln44_56_fu_1821_p2 - shl_ln44_85_fu_1827_p2);

assign sub_ln44_5_fu_1956_p2 = (sub_ln44_4_fu_1950_p2 - p_ZZ3firPiiE9shift_reg_103);

assign sub_ln44_6_fu_2743_p2 = (shl_ln44_6_fu_2738_p2 - p_ZZ3firPiiE9shift_reg_100_load_reg_3519_pp0_iter2_reg);

assign sub_ln44_7_fu_2419_p2 = (shl_ln44_8_fu_2414_p2 - fir_int_int_shift_reg_11_reg_3199_pp0_iter1_reg);

assign sub_ln44_8_fu_1329_p2 = (shl_ln44_9_fu_1317_p2 - shl_ln44_10_fu_1323_p2);

assign sub_ln44_9_fu_1335_p2 = (sub_ln44_8_fu_1329_p2 - p_ZZ3firPiiE9shift_reg_81);

assign sub_ln44_fu_2392_p2 = (32'd0 - shl_ln44_fu_2387_p2);

assign y = (add_ln44_46_reg_3899 + add_ln44_22_fu_3150_p2);

endmodule //fir
