// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="audio_audio,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.198000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=192,HLS_SYN_DSP=0,HLS_SYN_FF=1399,HLS_SYN_LUT=1023,HLS_VERSION=2024_2}" *)

module audio (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_L,
        out_L_ap_vld,
        out_R,
        out_R_ap_vld,
        in_L,
        in_R,
        delay_samples,
        feedback_gain,
        wet_mix
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] out_L;
output   out_L_ap_vld;
output  [31:0] out_R;
output   out_R_ap_vld;
input  [31:0] in_L;
input  [31:0] in_R;
input  [31:0] delay_samples;
input  [31:0] feedback_gain;
input  [31:0] wet_mix;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_L_ap_vld;
reg out_R_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] write_index;
wire   [23:0] delay_buffer_L_q0;
wire   [23:0] delay_buffer_R_q0;
reg   [15:0] write_index_load_reg_508;
wire   [15:0] read_index_2_fu_232_p3;
reg   [15:0] read_index_2_reg_513;
wire    ap_CS_fsm_state2;
reg  signed [23:0] delayed_L_reg_528;
wire    ap_CS_fsm_state3;
reg  signed [23:0] delayed_R_reg_533;
wire    ap_CS_fsm_state4;
wire  signed [31:0] sext_ln46_fu_271_p1;
wire  signed [31:0] sext_ln47_fu_276_p1;
wire  signed [31:0] sub_ln70_fu_281_p2;
reg  signed [31:0] sub_ln70_reg_562;
reg  signed [31:0] in_R_read_reg_568;
wire    ap_CS_fsm_state5;
reg  signed [31:0] in_L_read_reg_575;
reg   [23:0] feedback_from_R_reg_582;
reg   [23:0] feedback_from_L_reg_588;
reg   [23:0] tmp_reg_594;
reg   [23:0] tmp_2_reg_599;
wire   [31:0] add_ln52_fu_336_p2;
reg   [31:0] add_ln52_reg_604;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln56_fu_356_p2;
reg   [31:0] add_ln56_reg_609;
wire   [0:0] icmp_ln59_fu_377_p2;
reg   [0:0] icmp_ln59_reg_614;
wire   [0:0] icmp_ln61_fu_393_p2;
reg   [0:0] icmp_ln61_reg_619;
reg   [23:0] tmp_1_reg_624;
reg   [23:0] tmp_3_reg_629;
wire   [63:0] zext_ln46_fu_266_p1;
wire   [63:0] zext_ln65_fu_456_p1;
wire    ap_CS_fsm_state7;
wire   [15:0] select_ln80_fu_252_p3;
reg    delay_buffer_L_ce0_local;
reg   [15:0] delay_buffer_L_address0_local;
reg    delay_buffer_L_we0_local;
wire   [23:0] select_ln65_fu_447_p3;
reg    delay_buffer_R_ce0_local;
reg   [15:0] delay_buffer_R_address0_local;
reg    delay_buffer_R_we0_local;
wire   [23:0] select_ln66_fu_465_p3;
wire  signed [23:0] grp_fu_160_p0;
wire  signed [23:0] grp_fu_165_p0;
wire  signed [23:0] grp_fu_170_p0;
wire  signed [23:0] grp_fu_175_p0;
wire   [31:0] zext_ln39_fu_198_p1;
wire   [0:0] icmp_ln39_fu_202_p2;
wire   [15:0] trunc_ln87_fu_190_p1;
wire   [15:0] sub_ln42_fu_220_p2;
wire   [0:0] xor_ln39_fu_208_p2;
wire   [15:0] read_index_fu_214_p2;
wire   [15:0] read_index_1_fu_226_p2;
wire   [15:0] add_ln79_fu_240_p2;
wire   [0:0] icmp_ln80_fu_246_p2;
wire  signed [31:0] sub_ln70_fu_281_p1;
wire   [31:0] grp_fu_160_p2;
wire   [31:0] grp_fu_165_p2;
wire   [31:0] grp_fu_170_p2;
wire   [31:0] grp_fu_175_p2;
wire   [31:0] zext_ln51_1_fu_327_p1;
wire   [32:0] zext_ln51_fu_330_p1;
wire  signed [32:0] sext_ln52_fu_333_p1;
wire   [31:0] zext_ln55_1_fu_347_p1;
wire   [32:0] zext_ln55_fu_350_p1;
wire  signed [32:0] sext_ln56_fu_353_p1;
wire   [32:0] new_L_fu_341_p2;
wire   [9:0] tmp_4_fu_367_p4;
wire   [32:0] new_R_fu_361_p2;
wire   [9:0] tmp_5_fu_383_p4;
wire   [31:0] grp_fu_180_p2;
wire   [31:0] grp_fu_185_p2;
wire   [31:0] new_L_1_fu_419_p3;
wire   [31:0] new_R_1_fu_431_p3;
wire   [0:0] icmp_ln60_fu_425_p2;
wire   [23:0] trunc_ln65_fu_443_p1;
wire   [0:0] icmp_ln62_fu_437_p2;
wire   [23:0] trunc_ln66_fu_461_p1;
wire   [24:0] zext_ln70_fu_474_p1;
wire   [24:0] zext_ln71_fu_477_p1;
wire   [24:0] add_ln75_fu_486_p2;
wire   [24:0] zext_ln72_fu_480_p1;
wire   [24:0] zext_ln75_1_fu_483_p1;
wire   [24:0] add_ln76_fu_497_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 write_index = 16'd0;
end

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 48000 ),
    .AddressWidth( 16 ))
delay_buffer_L_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_buffer_L_address0_local),
    .ce0(delay_buffer_L_ce0_local),
    .we0(delay_buffer_L_we0_local),
    .d0(select_ln65_fu_447_p3),
    .q0(delay_buffer_L_q0)
);

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 48000 ),
    .AddressWidth( 16 ))
delay_buffer_R_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_buffer_R_address0_local),
    .ce0(delay_buffer_R_ce0_local),
    .we0(delay_buffer_R_we0_local),
    .d0(select_ln66_fu_465_p3),
    .q0(delay_buffer_R_q0)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_160_p0),
    .din1(feedback_gain),
    .ce(1'b1),
    .dout(grp_fu_160_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_165_p0),
    .din1(feedback_gain),
    .ce(1'b1),
    .dout(grp_fu_165_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_170_p0),
    .din1(wet_mix),
    .ce(1'b1),
    .dout(grp_fu_170_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_175_p0),
    .din1(wet_mix),
    .ce(1'b1),
    .dout(grp_fu_175_p2)
);

audio_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln70_reg_562),
    .din1(in_L),
    .ce(1'b1),
    .dout(grp_fu_180_p2)
);

audio_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln70_reg_562),
    .din1(in_R),
    .ce(1'b1),
    .dout(grp_fu_185_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln52_reg_604 <= add_ln52_fu_336_p2;
        add_ln56_reg_609 <= add_ln56_fu_356_p2;
        icmp_ln59_reg_614 <= icmp_ln59_fu_377_p2;
        icmp_ln61_reg_619 <= icmp_ln61_fu_393_p2;
        tmp_1_reg_624 <= {{grp_fu_180_p2[31:8]}};
        tmp_3_reg_629 <= {{grp_fu_185_p2[31:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delayed_L_reg_528 <= delay_buffer_L_q0;
        delayed_R_reg_533 <= delay_buffer_R_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        feedback_from_L_reg_588 <= {{grp_fu_165_p2[31:8]}};
        feedback_from_R_reg_582 <= {{grp_fu_160_p2[31:8]}};
        in_L_read_reg_575 <= in_L;
        in_R_read_reg_568 <= in_R;
        tmp_2_reg_599 <= {{grp_fu_175_p2[31:8]}};
        tmp_reg_594 <= {{grp_fu_170_p2[31:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        read_index_2_reg_513 <= read_index_2_fu_232_p3;
        write_index_load_reg_508 <= write_index;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sub_ln70_reg_562 <= sub_ln70_fu_281_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_index <= select_ln80_fu_252_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_L_address0_local = zext_ln65_fu_456_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_L_address0_local = zext_ln46_fu_266_p1;
    end else begin
        delay_buffer_L_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7))) begin
        delay_buffer_L_ce0_local = 1'b1;
    end else begin
        delay_buffer_L_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_L_we0_local = 1'b1;
    end else begin
        delay_buffer_L_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_R_address0_local = zext_ln65_fu_456_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_R_address0_local = zext_ln46_fu_266_p1;
    end else begin
        delay_buffer_R_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7))) begin
        delay_buffer_R_ce0_local = 1'b1;
    end else begin
        delay_buffer_R_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_R_we0_local = 1'b1;
    end else begin
        delay_buffer_R_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_L_ap_vld = 1'b1;
    end else begin
        out_L_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_R_ap_vld = 1'b1;
    end else begin
        out_R_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_336_p2 = ($signed(zext_ln51_1_fu_327_p1) + $signed(in_L_read_reg_575));

assign add_ln56_fu_356_p2 = ($signed(zext_ln55_1_fu_347_p1) + $signed(in_R_read_reg_568));

assign add_ln75_fu_486_p2 = (zext_ln70_fu_474_p1 + zext_ln71_fu_477_p1);

assign add_ln76_fu_497_p2 = (zext_ln72_fu_480_p1 + zext_ln75_1_fu_483_p1);

assign add_ln79_fu_240_p2 = (write_index + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign grp_fu_160_p0 = sext_ln47_fu_276_p1;

assign grp_fu_165_p0 = sext_ln46_fu_271_p1;

assign grp_fu_170_p0 = sext_ln46_fu_271_p1;

assign grp_fu_175_p0 = sext_ln47_fu_276_p1;

assign icmp_ln39_fu_202_p2 = ((zext_ln39_fu_198_p1 < delay_samples) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_377_p2 = (($signed(tmp_4_fu_367_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_425_p2 = (($signed(new_L_1_fu_419_p3) < $signed(32'd4286578688)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_393_p2 = (($signed(tmp_5_fu_383_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_437_p2 = (($signed(new_R_1_fu_431_p3) < $signed(32'd4286578688)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_246_p2 = ((add_ln79_fu_240_p2 > 16'd47999) ? 1'b1 : 1'b0);

assign new_L_1_fu_419_p3 = ((icmp_ln59_reg_614[0:0] == 1'b1) ? 32'd8388607 : add_ln52_reg_604);

assign new_L_fu_341_p2 = ($signed(zext_ln51_fu_330_p1) + $signed(sext_ln52_fu_333_p1));

assign new_R_1_fu_431_p3 = ((icmp_ln61_reg_619[0:0] == 1'b1) ? 32'd8388607 : add_ln56_reg_609);

assign new_R_fu_361_p2 = ($signed(zext_ln55_fu_350_p1) + $signed(sext_ln56_fu_353_p1));

assign out_L = add_ln75_fu_486_p2;

assign out_R = add_ln76_fu_497_p2;

assign read_index_1_fu_226_p2 = (write_index + sub_ln42_fu_220_p2);

assign read_index_2_fu_232_p3 = ((xor_ln39_fu_208_p2[0:0] == 1'b1) ? read_index_fu_214_p2 : read_index_1_fu_226_p2);

assign read_index_fu_214_p2 = (write_index - trunc_ln87_fu_190_p1);

assign select_ln65_fu_447_p3 = ((icmp_ln60_fu_425_p2[0:0] == 1'b1) ? 24'd8388608 : trunc_ln65_fu_443_p1);

assign select_ln66_fu_465_p3 = ((icmp_ln62_fu_437_p2[0:0] == 1'b1) ? 24'd8388608 : trunc_ln66_fu_461_p1);

assign select_ln80_fu_252_p3 = ((icmp_ln80_fu_246_p2[0:0] == 1'b1) ? 16'd0 : add_ln79_fu_240_p2);

assign sext_ln46_fu_271_p1 = delayed_L_reg_528;

assign sext_ln47_fu_276_p1 = delayed_R_reg_533;

assign sext_ln52_fu_333_p1 = in_L_read_reg_575;

assign sext_ln56_fu_353_p1 = in_R_read_reg_568;

assign sub_ln42_fu_220_p2 = ($signed(16'd48000) - $signed(trunc_ln87_fu_190_p1));

assign sub_ln70_fu_281_p1 = wet_mix;

assign sub_ln70_fu_281_p2 = ($signed(32'd256) - $signed(sub_ln70_fu_281_p1));

assign tmp_4_fu_367_p4 = {{new_L_fu_341_p2[32:23]}};

assign tmp_5_fu_383_p4 = {{new_R_fu_361_p2[32:23]}};

assign trunc_ln65_fu_443_p1 = new_L_1_fu_419_p3[23:0];

assign trunc_ln66_fu_461_p1 = new_R_1_fu_431_p3[23:0];

assign trunc_ln87_fu_190_p1 = delay_samples[15:0];

assign xor_ln39_fu_208_p2 = (icmp_ln39_fu_202_p2 ^ 1'd1);

assign zext_ln39_fu_198_p1 = write_index;

assign zext_ln46_fu_266_p1 = read_index_2_reg_513;

assign zext_ln51_1_fu_327_p1 = feedback_from_R_reg_582;

assign zext_ln51_fu_330_p1 = feedback_from_R_reg_582;

assign zext_ln55_1_fu_347_p1 = feedback_from_L_reg_588;

assign zext_ln55_fu_350_p1 = feedback_from_L_reg_588;

assign zext_ln65_fu_456_p1 = write_index_load_reg_508;

assign zext_ln70_fu_474_p1 = tmp_reg_594;

assign zext_ln71_fu_477_p1 = tmp_1_reg_624;

assign zext_ln72_fu_480_p1 = tmp_2_reg_599;

assign zext_ln75_1_fu_483_p1 = tmp_3_reg_629;

endmodule //audio
