// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="audio_audio,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.198000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=192,HLS_SYN_DSP=0,HLS_SYN_FF=1587,HLS_SYN_LUT=1319,HLS_VERSION=2024_2}" *)

module audio (
        ap_clk,
        ap_rst_n,
        delay_samples,
        feedback_gain,
        wet_mix,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] delay_samples;
input  [31:0] feedback_gain;
input  [31:0] wet_mix;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] out_L;
reg    out_L_ap_vld;
wire   [31:0] out_R;
reg    out_R_ap_vld;
wire   [31:0] in_L;
wire   [31:0] in_R;
reg   [15:0] write_index;
wire   [23:0] delay_buffer_L_q0;
wire   [23:0] delay_buffer_R_q0;
reg   [15:0] write_index_load_reg_522;
wire   [15:0] read_index_2_fu_246_p3;
reg   [15:0] read_index_2_reg_527;
wire    ap_CS_fsm_state2;
reg  signed [23:0] delayed_L_reg_542;
wire    ap_CS_fsm_state3;
reg  signed [23:0] delayed_R_reg_547;
wire    ap_CS_fsm_state4;
reg  signed [31:0] in_R_read_reg_564;
reg  signed [31:0] in_L_read_reg_571;
wire  signed [31:0] sext_ln46_fu_285_p1;
wire  signed [31:0] sext_ln47_fu_290_p1;
wire  signed [31:0] sub_ln70_fu_295_p2;
reg  signed [31:0] sub_ln70_reg_590;
reg   [23:0] feedback_from_R_reg_596;
wire    ap_CS_fsm_state5;
reg   [23:0] feedback_from_L_reg_602;
reg   [23:0] tmp_reg_608;
reg   [23:0] tmp_2_reg_613;
wire   [31:0] add_ln52_fu_350_p2;
reg   [31:0] add_ln52_reg_618;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln56_fu_370_p2;
reg   [31:0] add_ln56_reg_623;
wire   [0:0] icmp_ln59_fu_391_p2;
reg   [0:0] icmp_ln59_reg_628;
wire   [0:0] icmp_ln61_fu_407_p2;
reg   [0:0] icmp_ln61_reg_633;
reg   [23:0] tmp_1_reg_638;
reg   [23:0] tmp_3_reg_643;
wire   [63:0] zext_ln46_fu_280_p1;
wire   [63:0] zext_ln65_fu_470_p1;
wire    ap_CS_fsm_state7;
wire   [15:0] select_ln80_fu_266_p3;
reg    delay_buffer_L_ce0_local;
reg   [15:0] delay_buffer_L_address0_local;
reg    delay_buffer_L_we0_local;
wire   [23:0] select_ln65_fu_461_p3;
reg    delay_buffer_R_ce0_local;
reg   [15:0] delay_buffer_R_address0_local;
reg    delay_buffer_R_we0_local;
wire   [23:0] select_ln66_fu_479_p3;
wire  signed [23:0] grp_fu_176_p0;
wire  signed [23:0] grp_fu_181_p0;
wire  signed [23:0] grp_fu_186_p0;
wire  signed [23:0] grp_fu_191_p0;
wire   [31:0] zext_ln39_fu_212_p1;
wire   [0:0] icmp_ln39_fu_216_p2;
wire   [15:0] trunc_ln87_fu_204_p1;
wire   [15:0] sub_ln42_fu_234_p2;
wire   [0:0] xor_ln39_fu_222_p2;
wire   [15:0] read_index_fu_228_p2;
wire   [15:0] read_index_1_fu_240_p2;
wire   [15:0] add_ln79_fu_254_p2;
wire   [0:0] icmp_ln80_fu_260_p2;
wire  signed [31:0] sub_ln70_fu_295_p1;
wire   [31:0] grp_fu_176_p2;
wire   [31:0] grp_fu_181_p2;
wire   [31:0] grp_fu_186_p2;
wire   [31:0] grp_fu_191_p2;
wire   [31:0] zext_ln51_1_fu_341_p1;
wire   [32:0] zext_ln51_fu_344_p1;
wire  signed [32:0] sext_ln52_fu_347_p1;
wire   [31:0] zext_ln55_1_fu_361_p1;
wire   [32:0] zext_ln55_fu_364_p1;
wire  signed [32:0] sext_ln56_fu_367_p1;
wire   [32:0] new_L_fu_355_p2;
wire   [9:0] tmp_4_fu_381_p4;
wire   [32:0] new_R_fu_375_p2;
wire   [9:0] tmp_5_fu_397_p4;
wire   [31:0] grp_fu_196_p2;
wire   [31:0] grp_fu_200_p2;
wire   [31:0] new_L_1_fu_433_p3;
wire   [31:0] new_R_1_fu_445_p3;
wire   [0:0] icmp_ln60_fu_439_p2;
wire   [23:0] trunc_ln65_fu_457_p1;
wire   [0:0] icmp_ln62_fu_451_p2;
wire   [23:0] trunc_ln66_fu_475_p1;
wire   [24:0] zext_ln70_fu_488_p1;
wire   [24:0] zext_ln71_fu_491_p1;
wire   [24:0] add_ln75_fu_500_p2;
wire   [24:0] zext_ln72_fu_494_p1;
wire   [24:0] zext_ln75_1_fu_497_p1;
wire   [24:0] add_ln76_fu_511_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 write_index = 16'd0;
end

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 48000 ),
    .AddressWidth( 16 ))
delay_buffer_L_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(delay_buffer_L_address0_local),
    .ce0(delay_buffer_L_ce0_local),
    .we0(delay_buffer_L_we0_local),
    .d0(select_ln65_fu_461_p3),
    .q0(delay_buffer_L_q0)
);

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 48000 ),
    .AddressWidth( 16 ))
delay_buffer_R_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(delay_buffer_R_address0_local),
    .ce0(delay_buffer_R_ce0_local),
    .we0(delay_buffer_R_we0_local),
    .d0(select_ln66_fu_479_p3),
    .q0(delay_buffer_R_q0)
);

audio_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .out_L(out_L),
    .out_L_ap_vld(out_L_ap_vld),
    .out_R(out_R),
    .out_R_ap_vld(out_R_ap_vld),
    .in_L(in_L),
    .in_R(in_R),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_176_p0),
    .din1(feedback_gain),
    .ce(1'b1),
    .dout(grp_fu_176_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_181_p0),
    .din1(feedback_gain),
    .ce(1'b1),
    .dout(grp_fu_181_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_186_p0),
    .din1(wet_mix),
    .ce(1'b1),
    .dout(grp_fu_186_p2)
);

audio_mul_24s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_24s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_191_p0),
    .din1(wet_mix),
    .ce(1'b1),
    .dout(grp_fu_191_p2)
);

audio_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sub_ln70_reg_590),
    .din1(in_L_read_reg_571),
    .ce(1'b1),
    .dout(grp_fu_196_p2)
);

audio_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sub_ln70_reg_590),
    .din1(in_R_read_reg_564),
    .ce(1'b1),
    .dout(grp_fu_200_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln52_reg_618 <= add_ln52_fu_350_p2;
        add_ln56_reg_623 <= add_ln56_fu_370_p2;
        icmp_ln59_reg_628 <= icmp_ln59_fu_391_p2;
        icmp_ln61_reg_633 <= icmp_ln61_fu_407_p2;
        tmp_1_reg_638 <= {{grp_fu_196_p2[31:8]}};
        tmp_3_reg_643 <= {{grp_fu_200_p2[31:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delayed_L_reg_542 <= delay_buffer_L_q0;
        delayed_R_reg_547 <= delay_buffer_R_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        feedback_from_L_reg_602 <= {{grp_fu_181_p2[31:8]}};
        feedback_from_R_reg_596 <= {{grp_fu_176_p2[31:8]}};
        tmp_2_reg_613 <= {{grp_fu_191_p2[31:8]}};
        tmp_reg_608 <= {{grp_fu_186_p2[31:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_L_read_reg_571 <= in_L;
        in_R_read_reg_564 <= in_R;
        sub_ln70_reg_590 <= sub_ln70_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        read_index_2_reg_527 <= read_index_2_fu_246_p3;
        write_index_load_reg_522 <= write_index;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_index <= select_ln80_fu_266_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_L_address0_local = zext_ln65_fu_470_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_L_address0_local = zext_ln46_fu_280_p1;
    end else begin
        delay_buffer_L_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7))) begin
        delay_buffer_L_ce0_local = 1'b1;
    end else begin
        delay_buffer_L_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_L_we0_local = 1'b1;
    end else begin
        delay_buffer_L_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_R_address0_local = zext_ln65_fu_470_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_R_address0_local = zext_ln46_fu_280_p1;
    end else begin
        delay_buffer_R_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7))) begin
        delay_buffer_R_ce0_local = 1'b1;
    end else begin
        delay_buffer_R_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        delay_buffer_R_we0_local = 1'b1;
    end else begin
        delay_buffer_R_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_L_ap_vld = 1'b1;
    end else begin
        out_L_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_R_ap_vld = 1'b1;
    end else begin
        out_R_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_350_p2 = ($signed(zext_ln51_1_fu_341_p1) + $signed(in_L_read_reg_571));

assign add_ln56_fu_370_p2 = ($signed(zext_ln55_1_fu_361_p1) + $signed(in_R_read_reg_564));

assign add_ln75_fu_500_p2 = (zext_ln70_fu_488_p1 + zext_ln71_fu_491_p1);

assign add_ln76_fu_511_p2 = (zext_ln72_fu_494_p1 + zext_ln75_1_fu_497_p1);

assign add_ln79_fu_254_p2 = (write_index + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_176_p0 = sext_ln47_fu_290_p1;

assign grp_fu_181_p0 = sext_ln46_fu_285_p1;

assign grp_fu_186_p0 = sext_ln46_fu_285_p1;

assign grp_fu_191_p0 = sext_ln47_fu_290_p1;

assign icmp_ln39_fu_216_p2 = ((zext_ln39_fu_212_p1 < delay_samples) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_391_p2 = (($signed(tmp_4_fu_381_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_439_p2 = (($signed(new_L_1_fu_433_p3) < $signed(32'd4286578688)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_407_p2 = (($signed(tmp_5_fu_397_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_451_p2 = (($signed(new_R_1_fu_445_p3) < $signed(32'd4286578688)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_260_p2 = ((add_ln79_fu_254_p2 > 16'd47999) ? 1'b1 : 1'b0);

assign new_L_1_fu_433_p3 = ((icmp_ln59_reg_628[0:0] == 1'b1) ? 32'd8388607 : add_ln52_reg_618);

assign new_L_fu_355_p2 = ($signed(zext_ln51_fu_344_p1) + $signed(sext_ln52_fu_347_p1));

assign new_R_1_fu_445_p3 = ((icmp_ln61_reg_633[0:0] == 1'b1) ? 32'd8388607 : add_ln56_reg_623);

assign new_R_fu_375_p2 = ($signed(zext_ln55_fu_364_p1) + $signed(sext_ln56_fu_367_p1));

assign out_L = add_ln75_fu_500_p2;

assign out_R = add_ln76_fu_511_p2;

assign read_index_1_fu_240_p2 = (write_index + sub_ln42_fu_234_p2);

assign read_index_2_fu_246_p3 = ((xor_ln39_fu_222_p2[0:0] == 1'b1) ? read_index_fu_228_p2 : read_index_1_fu_240_p2);

assign read_index_fu_228_p2 = (write_index - trunc_ln87_fu_204_p1);

assign select_ln65_fu_461_p3 = ((icmp_ln60_fu_439_p2[0:0] == 1'b1) ? 24'd8388608 : trunc_ln65_fu_457_p1);

assign select_ln66_fu_479_p3 = ((icmp_ln62_fu_451_p2[0:0] == 1'b1) ? 24'd8388608 : trunc_ln66_fu_475_p1);

assign select_ln80_fu_266_p3 = ((icmp_ln80_fu_260_p2[0:0] == 1'b1) ? 16'd0 : add_ln79_fu_254_p2);

assign sext_ln46_fu_285_p1 = delayed_L_reg_542;

assign sext_ln47_fu_290_p1 = delayed_R_reg_547;

assign sext_ln52_fu_347_p1 = in_L_read_reg_571;

assign sext_ln56_fu_367_p1 = in_R_read_reg_564;

assign sub_ln42_fu_234_p2 = ($signed(16'd48000) - $signed(trunc_ln87_fu_204_p1));

assign sub_ln70_fu_295_p1 = wet_mix;

assign sub_ln70_fu_295_p2 = ($signed(32'd256) - $signed(sub_ln70_fu_295_p1));

assign tmp_4_fu_381_p4 = {{new_L_fu_355_p2[32:23]}};

assign tmp_5_fu_397_p4 = {{new_R_fu_375_p2[32:23]}};

assign trunc_ln65_fu_457_p1 = new_L_1_fu_433_p3[23:0];

assign trunc_ln66_fu_475_p1 = new_R_1_fu_445_p3[23:0];

assign trunc_ln87_fu_204_p1 = delay_samples[15:0];

assign xor_ln39_fu_222_p2 = (icmp_ln39_fu_216_p2 ^ 1'd1);

assign zext_ln39_fu_212_p1 = write_index;

assign zext_ln46_fu_280_p1 = read_index_2_reg_527;

assign zext_ln51_1_fu_341_p1 = feedback_from_R_reg_596;

assign zext_ln51_fu_344_p1 = feedback_from_R_reg_596;

assign zext_ln55_1_fu_361_p1 = feedback_from_L_reg_602;

assign zext_ln55_fu_364_p1 = feedback_from_L_reg_602;

assign zext_ln65_fu_470_p1 = write_index_load_reg_522;

assign zext_ln70_fu_488_p1 = tmp_reg_608;

assign zext_ln71_fu_491_p1 = tmp_1_reg_638;

assign zext_ln72_fu_494_p1 = tmp_2_reg_613;

assign zext_ln75_1_fu_497_p1 = tmp_3_reg_643;

endmodule //audio
