// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_Shift_Accum_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul,
        x,
        acc_1_out,
        acc_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mul;
input  [31:0] x;
output  [31:0] acc_1_out;
output   acc_1_out_ap_vld;

reg ap_idle;
reg acc_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_134_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] shift_reg_address0;
wire   [31:0] shift_reg_q1;
wire   [6:0] fir_int_int_c_address0;
wire   [31:0] fir_int_int_c_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln31_reg_201;
reg   [0:0] icmp_ln31_reg_201_pp0_iter1_reg;
reg   [0:0] icmp_ln31_reg_201_pp0_iter2_reg;
reg   [0:0] icmp_ln31_reg_201_pp0_iter3_reg;
wire   [63:0] zext_ln30_fu_151_p1;
reg   [63:0] zext_ln30_reg_210;
reg  signed [31:0] shift_reg_load_reg_220;
reg  signed [31:0] fir_int_int_c_load_reg_225;
wire   [31:0] grp_fu_117_p2;
reg   [31:0] mul_ln36_reg_230;
reg   [31:0] ap_phi_mux_mul_pn_phi_fu_111_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_mul_pn_reg_108;
reg   [31:0] ap_phi_reg_pp0_iter1_mul_pn_reg_108;
reg   [31:0] ap_phi_reg_pp0_iter2_mul_pn_reg_108;
reg   [31:0] ap_phi_reg_pp0_iter3_mul_pn_reg_108;
reg   [31:0] ap_phi_reg_pp0_iter4_mul_pn_reg_108;
wire   [63:0] zext_ln35_fu_146_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i1_fu_40;
wire   [6:0] i_fu_156_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i1_load;
reg   [31:0] acc2_fu_44;
wire   [31:0] acc_fu_170_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
wire    ap_block_pp0_stage0_01001;
reg    shift_reg_ce1_local;
reg   [6:0] shift_reg_address1_local;
reg    shift_reg_we1_local;
reg    shift_reg_we0_local;
reg    shift_reg_ce0_local;
reg    fir_int_int_c_ce0_local;
wire  signed [5:0] grp_fu_117_p0;
wire   [6:0] add_ln35_fu_140_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_118;
reg    ap_condition_139;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 i1_fu_40 = 7'd0;
#0 acc2_fu_44 = 32'd0;
#0 ap_done_reg = 1'b0;
end

fir_fir_Pipeline_Shift_Accum_Loop_shift_reg_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
shift_reg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(shift_reg_address0),
    .ce0(shift_reg_ce0_local),
    .we0(shift_reg_we0_local),
    .d0(shift_reg_q1),
    .address1(shift_reg_address1_local),
    .ce1(shift_reg_ce1_local),
    .we1(shift_reg_we1_local),
    .d1(x),
    .q1(shift_reg_q1)
);

fir_fir_Pipeline_Shift_Accum_Loop_fir_int_int_c_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
fir_int_int_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fir_int_int_c_address0),
    .ce0(fir_int_int_c_ce0_local),
    .q0(fir_int_int_c_q0)
);

fir_mul_6s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_6s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_117_p0),
    .din1(shift_reg_load_reg_220),
    .ce(1'b1),
    .dout(grp_fu_117_p2)
);

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc2_fu_44 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            acc2_fu_44 <= acc_fu_170_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_118)) begin
        if ((icmp_ln31_fu_134_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_mul_pn_reg_108 <= mul;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_mul_pn_reg_108 <= ap_phi_reg_pp0_iter0_mul_pn_reg_108;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            i1_fu_40 <= i_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i1_fu_40 <= 7'd127;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        fir_int_int_c_load_reg_225 <= fir_int_int_c_q0;
        icmp_ln31_reg_201 <= icmp_ln31_fu_134_p2;
        icmp_ln31_reg_201_pp0_iter1_reg <= icmp_ln31_reg_201;
        zext_ln30_reg_210[6 : 0] <= zext_ln30_fu_151_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln31_reg_201_pp0_iter2_reg <= icmp_ln31_reg_201_pp0_iter1_reg;
        icmp_ln31_reg_201_pp0_iter3_reg <= icmp_ln31_reg_201_pp0_iter2_reg;
        mul_ln36_reg_230 <= grp_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_mul_pn_reg_108 <= ap_phi_reg_pp0_iter1_mul_pn_reg_108;
        shift_reg_load_reg_220 <= shift_reg_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_mul_pn_reg_108 <= ap_phi_reg_pp0_iter2_mul_pn_reg_108;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_mul_pn_reg_108 <= ap_phi_reg_pp0_iter3_mul_pn_reg_108;
    end
end

always @ (*) begin
    if (((icmp_ln31_reg_201_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        acc_1_out_ap_vld = 1'b1;
    end else begin
        acc_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_134_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln31_reg_201_pp0_iter3_reg == 1'd0)) begin
        ap_phi_mux_mul_pn_phi_fu_111_p4 = mul_ln36_reg_230;
    end else begin
        ap_phi_mux_mul_pn_phi_fu_111_p4 = ap_phi_reg_pp0_iter4_mul_pn_reg_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_load = 7'd127;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fir_int_int_c_ce0_local = 1'b1;
    end else begin
        fir_int_int_c_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_139)) begin
        if ((icmp_ln31_fu_134_p2 == 1'd1)) begin
            shift_reg_address1_local = 7'd0;
        end else if ((icmp_ln31_fu_134_p2 == 1'd0)) begin
            shift_reg_address1_local = zext_ln35_fu_146_p1;
        end else begin
            shift_reg_address1_local = 'bx;
        end
    end else begin
        shift_reg_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_ce0_local = 1'b1;
    end else begin
        shift_reg_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln31_fu_134_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln31_fu_134_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        shift_reg_ce1_local = 1'b1;
    end else begin
        shift_reg_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_reg_201 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_we0_local = 1'b1;
    end else begin
        shift_reg_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_134_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_we1_local = 1'b1;
    end else begin
        shift_reg_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_out = (ap_phi_mux_mul_pn_phi_fu_111_p4 + acc2_fu_44);

assign acc_fu_170_p2 = (ap_phi_mux_mul_pn_phi_fu_111_p4 + acc2_fu_44);

assign add_ln35_fu_140_p2 = ($signed(ap_sig_allocacmp_i1_load) + $signed(7'd127));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_118 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_139 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_mul_pn_reg_108 = 'bx;

assign ap_ready = ap_ready_sig;

assign fir_int_int_c_address0 = zext_ln30_fu_151_p1;

assign grp_fu_117_p0 = fir_int_int_c_load_reg_225;

assign i_fu_156_p2 = ($signed(ap_sig_allocacmp_i1_load) + $signed(7'd127));

assign icmp_ln31_fu_134_p2 = ((ap_sig_allocacmp_i1_load == 7'd0) ? 1'b1 : 1'b0);

assign shift_reg_address0 = zext_ln30_reg_210;

assign zext_ln30_fu_151_p1 = ap_sig_allocacmp_i1_load;

assign zext_ln35_fu_146_p1 = add_ln35_fu_140_p2;

always @ (posedge ap_clk) begin
    zext_ln30_reg_210[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //fir_fir_Pipeline_Shift_Accum_Loop
