# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8.xci
# IP: The module: 'base_m05_regslice_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m05_regslice_8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m05_regslice_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8.xci
# IP: The module: 'base_m05_regslice_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m05_regslice_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/james/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m05_regslice_8/base_m05_regslice_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m05_regslice_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
