-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_L : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_L_ap_vld : OUT STD_LOGIC;
    out_R : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_R_ap_vld : OUT STD_LOGIC;
    in_L : IN STD_LOGIC_VECTOR (31 downto 0);
    in_R : IN STD_LOGIC_VECTOR (31 downto 0);
    delay_samples : IN STD_LOGIC_VECTOR (31 downto 0);
    feedback_gain : IN STD_LOGIC_VECTOR (31 downto 0);
    wet_mix : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of audio is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "audio_audio,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.198000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=192,HLS_SYN_DSP=0,HLS_SYN_FF=1399,HLS_SYN_LUT=1023,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_BB80 : STD_LOGIC_VECTOR (15 downto 0) := "1011101110000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_BB7F : STD_LOGIC_VECTOR (15 downto 0) := "1011101101111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_7FFFFF : STD_LOGIC_VECTOR (31 downto 0) := "00000000011111111111111111111111";
    constant ap_const_lv32_FF800000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111100000000000000000000000";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal write_index : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal delay_buffer_L_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal delay_buffer_R_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal write_index_load_reg_508 : STD_LOGIC_VECTOR (15 downto 0);
    signal read_index_2_fu_232_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal read_index_2_reg_513 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal delayed_L_reg_528 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal delayed_R_reg_533 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln52_fu_271_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln53_fu_276_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln76_fu_281_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln76_reg_562 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_R_read_reg_568 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal in_L_read_reg_575 : STD_LOGIC_VECTOR (31 downto 0);
    signal feedback_from_R_reg_582 : STD_LOGIC_VECTOR (23 downto 0);
    signal feedback_from_L_reg_588 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_reg_594 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_reg_599 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln58_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln58_reg_604 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln62_fu_356_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln62_reg_609 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln65_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_614 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_624 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_3_reg_629 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln52_fu_266_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_fu_456_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal select_ln86_fu_252_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal delay_buffer_L_ce0_local : STD_LOGIC;
    signal delay_buffer_L_address0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal delay_buffer_L_we0_local : STD_LOGIC;
    signal select_ln71_fu_447_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal delay_buffer_R_ce0_local : STD_LOGIC;
    signal delay_buffer_R_address0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal delay_buffer_R_we0_local : STD_LOGIC;
    signal select_ln72_fu_465_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_160_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_165_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_170_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_175_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln45_fu_198_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln45_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln93_fu_190_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln48_fu_220_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln45_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal read_index_fu_214_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal read_index_1_fu_226_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln85_fu_240_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln86_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln76_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_165_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_170_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_175_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln57_1_fu_327_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln57_fu_330_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln58_fu_333_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln61_1_fu_347_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln61_fu_350_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln62_fu_353_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal new_L_fu_341_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_4_fu_367_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal new_R_fu_361_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_5_fu_383_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_185_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_L_1_fu_419_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_R_1_fu_431_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln66_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln71_fu_443_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln68_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln72_fu_461_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln76_fu_474_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln77_fu_477_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln81_fu_486_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln78_fu_480_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln81_1_fu_483_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln82_fu_497_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_mul_24s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component audio_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component audio_delay_buffer_L_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    delay_buffer_L_U : component audio_delay_buffer_L_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 48000,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => delay_buffer_L_address0_local,
        ce0 => delay_buffer_L_ce0_local,
        we0 => delay_buffer_L_we0_local,
        d0 => select_ln71_fu_447_p3,
        q0 => delay_buffer_L_q0);

    delay_buffer_R_U : component audio_delay_buffer_L_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 48000,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => delay_buffer_R_address0_local,
        ce0 => delay_buffer_R_ce0_local,
        we0 => delay_buffer_R_we0_local,
        d0 => select_ln72_fu_465_p3,
        q0 => delay_buffer_R_q0);

    mul_24s_32s_32_2_1_U1 : component audio_mul_24s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 24,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_160_p0,
        din1 => feedback_gain,
        ce => ap_const_logic_1,
        dout => grp_fu_160_p2);

    mul_24s_32s_32_2_1_U2 : component audio_mul_24s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 24,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_165_p0,
        din1 => feedback_gain,
        ce => ap_const_logic_1,
        dout => grp_fu_165_p2);

    mul_24s_32s_32_2_1_U3 : component audio_mul_24s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 24,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_170_p0,
        din1 => wet_mix,
        ce => ap_const_logic_1,
        dout => grp_fu_170_p2);

    mul_24s_32s_32_2_1_U4 : component audio_mul_24s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 24,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_175_p0,
        din1 => wet_mix,
        ce => ap_const_logic_1,
        dout => grp_fu_175_p2);

    mul_32s_32s_32_2_1_U5 : component audio_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_ln76_reg_562,
        din1 => in_L,
        ce => ap_const_logic_1,
        dout => grp_fu_180_p2);

    mul_32s_32s_32_2_1_U6 : component audio_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_ln76_reg_562,
        din1 => in_R,
        ce => ap_const_logic_1,
        dout => grp_fu_185_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln58_reg_604 <= add_ln58_fu_336_p2;
                add_ln62_reg_609 <= add_ln62_fu_356_p2;
                icmp_ln65_reg_614 <= icmp_ln65_fu_377_p2;
                icmp_ln67_reg_619 <= icmp_ln67_fu_393_p2;
                tmp_1_reg_624 <= grp_fu_180_p2(31 downto 8);
                tmp_3_reg_629 <= grp_fu_185_p2(31 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                delayed_L_reg_528 <= delay_buffer_L_q0;
                delayed_R_reg_533 <= delay_buffer_R_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                feedback_from_L_reg_588 <= grp_fu_165_p2(31 downto 8);
                feedback_from_R_reg_582 <= grp_fu_160_p2(31 downto 8);
                in_L_read_reg_575 <= in_L;
                in_R_read_reg_568 <= in_R;
                tmp_2_reg_599 <= grp_fu_175_p2(31 downto 8);
                tmp_reg_594 <= grp_fu_170_p2(31 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                read_index_2_reg_513 <= read_index_2_fu_232_p3;
                write_index_load_reg_508 <= write_index;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sub_ln76_reg_562 <= sub_ln76_fu_281_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                write_index <= select_ln86_fu_252_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln58_fu_336_p2 <= std_logic_vector(unsigned(zext_ln57_1_fu_327_p1) + unsigned(in_L_read_reg_575));
    add_ln62_fu_356_p2 <= std_logic_vector(unsigned(zext_ln61_1_fu_347_p1) + unsigned(in_R_read_reg_568));
    add_ln81_fu_486_p2 <= std_logic_vector(unsigned(zext_ln76_fu_474_p1) + unsigned(zext_ln77_fu_477_p1));
    add_ln82_fu_497_p2 <= std_logic_vector(unsigned(zext_ln78_fu_480_p1) + unsigned(zext_ln81_1_fu_483_p1));
    add_ln85_fu_240_p2 <= std_logic_vector(unsigned(write_index) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_L_address0_local_assign_proc : process(ap_CS_fsm_state2, zext_ln52_fu_266_p1, zext_ln71_fu_456_p1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            delay_buffer_L_address0_local <= zext_ln71_fu_456_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_L_address0_local <= zext_ln52_fu_266_p1(16 - 1 downto 0);
        else 
            delay_buffer_L_address0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    delay_buffer_L_ce0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            delay_buffer_L_ce0_local <= ap_const_logic_1;
        else 
            delay_buffer_L_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_L_we0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            delay_buffer_L_we0_local <= ap_const_logic_1;
        else 
            delay_buffer_L_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_R_address0_local_assign_proc : process(ap_CS_fsm_state2, zext_ln52_fu_266_p1, zext_ln71_fu_456_p1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            delay_buffer_R_address0_local <= zext_ln71_fu_456_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            delay_buffer_R_address0_local <= zext_ln52_fu_266_p1(16 - 1 downto 0);
        else 
            delay_buffer_R_address0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    delay_buffer_R_ce0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            delay_buffer_R_ce0_local <= ap_const_logic_1;
        else 
            delay_buffer_R_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    delay_buffer_R_we0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            delay_buffer_R_we0_local <= ap_const_logic_1;
        else 
            delay_buffer_R_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_160_p0 <= sext_ln53_fu_276_p1(24 - 1 downto 0);
    grp_fu_165_p0 <= sext_ln52_fu_271_p1(24 - 1 downto 0);
    grp_fu_170_p0 <= sext_ln52_fu_271_p1(24 - 1 downto 0);
    grp_fu_175_p0 <= sext_ln53_fu_276_p1(24 - 1 downto 0);
    icmp_ln45_fu_202_p2 <= "1" when (unsigned(zext_ln45_fu_198_p1) < unsigned(delay_samples)) else "0";
    icmp_ln65_fu_377_p2 <= "1" when (signed(tmp_4_fu_367_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln66_fu_425_p2 <= "1" when (signed(new_L_1_fu_419_p3) < signed(ap_const_lv32_FF800000)) else "0";
    icmp_ln67_fu_393_p2 <= "1" when (signed(tmp_5_fu_383_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln68_fu_437_p2 <= "1" when (signed(new_R_1_fu_431_p3) < signed(ap_const_lv32_FF800000)) else "0";
    icmp_ln86_fu_246_p2 <= "1" when (unsigned(add_ln85_fu_240_p2) > unsigned(ap_const_lv16_BB7F)) else "0";
    new_L_1_fu_419_p3 <= 
        ap_const_lv32_7FFFFF when (icmp_ln65_reg_614(0) = '1') else 
        add_ln58_reg_604;
    new_L_fu_341_p2 <= std_logic_vector(unsigned(zext_ln57_fu_330_p1) + unsigned(sext_ln58_fu_333_p1));
    new_R_1_fu_431_p3 <= 
        ap_const_lv32_7FFFFF when (icmp_ln67_reg_619(0) = '1') else 
        add_ln62_reg_609;
    new_R_fu_361_p2 <= std_logic_vector(unsigned(zext_ln61_fu_350_p1) + unsigned(sext_ln62_fu_353_p1));
    out_L <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln81_fu_486_p2),32));

    out_L_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_L_ap_vld <= ap_const_logic_1;
        else 
            out_L_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_R <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln82_fu_497_p2),32));

    out_R_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_R_ap_vld <= ap_const_logic_1;
        else 
            out_R_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    read_index_1_fu_226_p2 <= std_logic_vector(unsigned(write_index) + unsigned(sub_ln48_fu_220_p2));
    read_index_2_fu_232_p3 <= 
        read_index_fu_214_p2 when (xor_ln45_fu_208_p2(0) = '1') else 
        read_index_1_fu_226_p2;
    read_index_fu_214_p2 <= std_logic_vector(unsigned(write_index) - unsigned(trunc_ln93_fu_190_p1));
    select_ln71_fu_447_p3 <= 
        ap_const_lv24_800000 when (icmp_ln66_fu_425_p2(0) = '1') else 
        trunc_ln71_fu_443_p1;
    select_ln72_fu_465_p3 <= 
        ap_const_lv24_800000 when (icmp_ln68_fu_437_p2(0) = '1') else 
        trunc_ln72_fu_461_p1;
    select_ln86_fu_252_p3 <= 
        ap_const_lv16_0 when (icmp_ln86_fu_246_p2(0) = '1') else 
        add_ln85_fu_240_p2;
        sext_ln52_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delayed_L_reg_528),32));

        sext_ln53_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delayed_R_reg_533),32));

        sext_ln58_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_L_read_reg_575),33));

        sext_ln62_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_R_read_reg_568),33));

    sub_ln48_fu_220_p2 <= std_logic_vector(signed(ap_const_lv16_BB80) - signed(trunc_ln93_fu_190_p1));
    sub_ln76_fu_281_p1 <= wet_mix;
    sub_ln76_fu_281_p2 <= std_logic_vector(unsigned(ap_const_lv32_100) - unsigned(sub_ln76_fu_281_p1));
    tmp_4_fu_367_p4 <= new_L_fu_341_p2(32 downto 23);
    tmp_5_fu_383_p4 <= new_R_fu_361_p2(32 downto 23);
    trunc_ln71_fu_443_p1 <= new_L_1_fu_419_p3(24 - 1 downto 0);
    trunc_ln72_fu_461_p1 <= new_R_1_fu_431_p3(24 - 1 downto 0);
    trunc_ln93_fu_190_p1 <= delay_samples(16 - 1 downto 0);
    xor_ln45_fu_208_p2 <= (icmp_ln45_fu_202_p2 xor ap_const_lv1_1);
    zext_ln45_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(write_index),32));
    zext_ln52_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_index_2_reg_513),64));
    zext_ln57_1_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(feedback_from_R_reg_582),32));
    zext_ln57_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(feedback_from_R_reg_582),33));
    zext_ln61_1_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(feedback_from_L_reg_588),32));
    zext_ln61_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(feedback_from_L_reg_588),33));
    zext_ln71_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(write_index_load_reg_508),64));
    zext_ln76_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_594),25));
    zext_ln77_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_624),25));
    zext_ln78_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_599),25));
    zext_ln81_1_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_629),25));
end behav;
