// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="audio_audio,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=0,HLS_SYN_FF=1635,HLS_SYN_LUT=1203,HLS_VERSION=2024_2}" *)

module audio (
        ap_clk,
        ap_rst_n,
        delay_samples,
        feedback_gain,
        wet_mix,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] delay_samples;
input  [31:0] feedback_gain;
input  [31:0] wet_mix;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] out_L;
reg    out_L_ap_vld;
wire   [31:0] out_R;
reg    out_R_ap_vld;
wire   [31:0] in_L;
wire   [31:0] in_R;
reg   [31:0] write_index;
wire   [31:0] delay_buffer_L_q0;
wire   [31:0] delay_buffer_R_q0;
wire   [12:0] trunc_ln38_fu_182_p1;
reg   [12:0] trunc_ln38_reg_453;
reg   [31:0] wet_mix_read_reg_468;
wire    ap_CS_fsm_state2;
reg  signed [31:0] in_R_read_reg_473;
reg  signed [31:0] in_L_read_reg_478;
reg  signed [31:0] delayed_L_reg_483;
reg  signed [31:0] delayed_R_reg_488;
wire   [31:0] sub_ln65_fu_215_p2;
reg   [31:0] sub_ln65_reg_493;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln64_fu_225_p1;
wire   [63:0] zext_ln65_fu_234_p1;
wire   [63:0] grp_fu_166_p2;
reg   [63:0] mul_ln64_reg_530;
wire    ap_CS_fsm_state4;
wire   [39:0] trunc_ln64_fu_247_p1;
reg   [39:0] trunc_ln64_reg_536;
wire   [63:0] grp_fu_158_p2;
reg   [63:0] mul_ln65_reg_541;
wire   [39:0] trunc_ln65_fu_251_p1;
reg   [39:0] trunc_ln65_reg_547;
wire   [63:0] grp_fu_170_p2;
reg   [63:0] mul_ln66_reg_552;
wire   [39:0] trunc_ln66_fu_255_p1;
reg   [39:0] trunc_ln66_reg_558;
wire   [63:0] grp_fu_162_p2;
reg   [63:0] mul_ln67_reg_563;
wire   [39:0] trunc_ln67_fu_259_p1;
reg   [39:0] trunc_ln67_reg_569;
reg   [31:0] trunc_ln64_1_reg_574;
wire    ap_CS_fsm_state5;
reg   [31:0] trunc_ln65_1_reg_579;
reg   [31:0] trunc_ln66_1_reg_584;
reg   [31:0] trunc_ln67_1_reg_589;
wire   [63:0] zext_ln41_fu_192_p1;
wire   [63:0] zext_ln60_fu_210_p1;
wire   [31:0] add_ln74_fu_198_p2;
wire    ap_CS_fsm_state6;
reg    delay_buffer_L_ce0_local;
reg   [12:0] delay_buffer_L_address0_local;
reg    delay_buffer_L_we0_local;
reg    delay_buffer_R_ce0_local;
reg   [12:0] delay_buffer_R_address0_local;
reg    delay_buffer_R_we0_local;
wire   [31:0] grp_fu_158_p0;
wire   [31:0] grp_fu_162_p0;
wire   [31:0] grp_fu_166_p1;
wire   [31:0] grp_fu_170_p1;
wire   [12:0] trunc_ln82_fu_174_p1;
wire   [12:0] read_index_fu_186_p2;
wire   [39:0] sub_ln64_fu_263_p2;
wire   [39:0] sub_ln65_1_fu_278_p2;
wire   [39:0] sub_ln66_fu_293_p2;
wire   [39:0] sub_ln67_fu_308_p2;
wire   [0:0] tmp_fu_323_p3;
wire   [31:0] sub_ln64_1_fu_330_p2;
wire   [31:0] trunc_ln64_2_fu_335_p4;
wire   [0:0] tmp_1_fu_352_p3;
wire   [31:0] sub_ln65_2_fu_359_p2;
wire   [31:0] trunc_ln65_2_fu_364_p4;
wire   [0:0] tmp_2_fu_381_p3;
wire   [31:0] sub_ln66_1_fu_388_p2;
wire   [31:0] trunc_ln66_2_fu_393_p4;
wire   [0:0] tmp_3_fu_410_p3;
wire   [31:0] sub_ln67_1_fu_417_p2;
wire   [31:0] trunc_ln67_2_fu_422_p4;
wire   [31:0] select_ln65_fu_373_p3;
wire   [31:0] select_ln64_fu_344_p3;
wire   [31:0] select_ln67_fu_431_p3;
wire   [31:0] select_ln66_fu_402_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 write_index = 32'd0;
end

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
delay_buffer_L_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(delay_buffer_L_address0_local),
    .ce0(delay_buffer_L_ce0_local),
    .we0(delay_buffer_L_we0_local),
    .d0(in_L),
    .q0(delay_buffer_L_q0)
);

audio_delay_buffer_L_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
delay_buffer_R_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(delay_buffer_R_address0_local),
    .ce0(delay_buffer_R_ce0_local),
    .we0(delay_buffer_R_we0_local),
    .d0(in_R),
    .q0(delay_buffer_R_q0)
);

audio_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .out_L(out_L),
    .out_L_ap_vld(out_L_ap_vld),
    .out_R(out_R),
    .out_R_ap_vld(out_R_ap_vld),
    .in_L(in_L),
    .in_R(in_R),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

audio_mul_32ns_32s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32s_64_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_158_p0),
    .din1(in_L_read_reg_478),
    .ce(1'b1),
    .dout(grp_fu_158_p2)
);

audio_mul_32ns_32s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32s_64_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_162_p0),
    .din1(in_R_read_reg_473),
    .ce(1'b1),
    .dout(grp_fu_162_p2)
);

audio_mul_32s_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32ns_64_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(delayed_L_reg_483),
    .din1(grp_fu_166_p1),
    .ce(1'b1),
    .dout(grp_fu_166_p2)
);

audio_mul_32s_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32ns_64_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(delayed_R_reg_488),
    .din1(grp_fu_170_p1),
    .ce(1'b1),
    .dout(grp_fu_170_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delayed_L_reg_483 <= delay_buffer_L_q0;
        delayed_R_reg_488 <= delay_buffer_R_q0;
        in_L_read_reg_478 <= in_L;
        in_R_read_reg_473 <= in_R;
        sub_ln65_reg_493 <= sub_ln65_fu_215_p2;
        wet_mix_read_reg_468 <= wet_mix;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln64_reg_530 <= grp_fu_166_p2;
        mul_ln65_reg_541 <= grp_fu_158_p2;
        mul_ln66_reg_552 <= grp_fu_170_p2;
        mul_ln67_reg_563 <= grp_fu_162_p2;
        trunc_ln64_reg_536 <= trunc_ln64_fu_247_p1;
        trunc_ln65_reg_547 <= trunc_ln65_fu_251_p1;
        trunc_ln66_reg_558 <= trunc_ln66_fu_255_p1;
        trunc_ln67_reg_569 <= trunc_ln67_fu_259_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln38_reg_453 <= trunc_ln38_fu_182_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln64_1_reg_574 <= {{sub_ln64_fu_263_p2[39:8]}};
        trunc_ln65_1_reg_579 <= {{sub_ln65_1_fu_278_p2[39:8]}};
        trunc_ln66_1_reg_584 <= {{sub_ln66_fu_293_p2[39:8]}};
        trunc_ln67_1_reg_589 <= {{sub_ln67_fu_308_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        write_index <= add_ln74_fu_198_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_L_address0_local = zext_ln60_fu_210_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        delay_buffer_L_address0_local = zext_ln41_fu_192_p1;
    end else begin
        delay_buffer_L_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        delay_buffer_L_ce0_local = 1'b1;
    end else begin
        delay_buffer_L_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_L_we0_local = 1'b1;
    end else begin
        delay_buffer_L_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_R_address0_local = zext_ln60_fu_210_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        delay_buffer_R_address0_local = zext_ln41_fu_192_p1;
    end else begin
        delay_buffer_R_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        delay_buffer_R_ce0_local = 1'b1;
    end else begin
        delay_buffer_R_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_buffer_R_we0_local = 1'b1;
    end else begin
        delay_buffer_R_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_L_ap_vld = 1'b1;
    end else begin
        out_L_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_R_ap_vld = 1'b1;
    end else begin
        out_R_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_fu_198_p2 = (write_index + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_158_p0 = zext_ln65_fu_234_p1;

assign grp_fu_162_p0 = zext_ln65_fu_234_p1;

assign grp_fu_166_p1 = zext_ln64_fu_225_p1;

assign grp_fu_170_p1 = zext_ln64_fu_225_p1;

assign out_L = (select_ln65_fu_373_p3 + select_ln64_fu_344_p3);

assign out_R = (select_ln67_fu_431_p3 + select_ln66_fu_402_p3);

assign read_index_fu_186_p2 = (trunc_ln38_fu_182_p1 - trunc_ln82_fu_174_p1);

assign select_ln64_fu_344_p3 = ((tmp_fu_323_p3[0:0] == 1'b1) ? sub_ln64_1_fu_330_p2 : trunc_ln64_2_fu_335_p4);

assign select_ln65_fu_373_p3 = ((tmp_1_fu_352_p3[0:0] == 1'b1) ? sub_ln65_2_fu_359_p2 : trunc_ln65_2_fu_364_p4);

assign select_ln66_fu_402_p3 = ((tmp_2_fu_381_p3[0:0] == 1'b1) ? sub_ln66_1_fu_388_p2 : trunc_ln66_2_fu_393_p4);

assign select_ln67_fu_431_p3 = ((tmp_3_fu_410_p3[0:0] == 1'b1) ? sub_ln67_1_fu_417_p2 : trunc_ln67_2_fu_422_p4);

assign sub_ln64_1_fu_330_p2 = (32'd0 - trunc_ln64_1_reg_574);

assign sub_ln64_fu_263_p2 = (40'd0 - trunc_ln64_reg_536);

assign sub_ln65_1_fu_278_p2 = (40'd0 - trunc_ln65_reg_547);

assign sub_ln65_2_fu_359_p2 = (32'd0 - trunc_ln65_1_reg_579);

assign sub_ln65_fu_215_p2 = (32'd256 - wet_mix);

assign sub_ln66_1_fu_388_p2 = (32'd0 - trunc_ln66_1_reg_584);

assign sub_ln66_fu_293_p2 = (40'd0 - trunc_ln66_reg_558);

assign sub_ln67_1_fu_417_p2 = (32'd0 - trunc_ln67_1_reg_589);

assign sub_ln67_fu_308_p2 = (40'd0 - trunc_ln67_reg_569);

assign tmp_1_fu_352_p3 = mul_ln65_reg_541[32'd63];

assign tmp_2_fu_381_p3 = mul_ln66_reg_552[32'd63];

assign tmp_3_fu_410_p3 = mul_ln67_reg_563[32'd63];

assign tmp_fu_323_p3 = mul_ln64_reg_530[32'd63];

assign trunc_ln38_fu_182_p1 = write_index[12:0];

assign trunc_ln64_2_fu_335_p4 = {{mul_ln64_reg_530[39:8]}};

assign trunc_ln64_fu_247_p1 = grp_fu_166_p2[39:0];

assign trunc_ln65_2_fu_364_p4 = {{mul_ln65_reg_541[39:8]}};

assign trunc_ln65_fu_251_p1 = grp_fu_158_p2[39:0];

assign trunc_ln66_2_fu_393_p4 = {{mul_ln66_reg_552[39:8]}};

assign trunc_ln66_fu_255_p1 = grp_fu_170_p2[39:0];

assign trunc_ln67_2_fu_422_p4 = {{mul_ln67_reg_563[39:8]}};

assign trunc_ln67_fu_259_p1 = grp_fu_162_p2[39:0];

assign trunc_ln82_fu_174_p1 = delay_samples[12:0];

assign zext_ln41_fu_192_p1 = read_index_fu_186_p2;

assign zext_ln60_fu_210_p1 = trunc_ln38_reg_453;

assign zext_ln64_fu_225_p1 = wet_mix_read_reg_468;

assign zext_ln65_fu_234_p1 = sub_ln65_reg_493;

endmodule //audio
